### ISSUE TITLE
Keep scroll position after selecting item from virtual list

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#102]
Hi, would it be possible to keep the scroll position after user selects item from the virtual list ?

Sometimes it stays and sometimes it doesn't and jumps back at the top. I don't know why. From what I can tell, it scrolls up by the current dropdown height.

Svelecte 3.6.0

**Comment by mskocik** [comment]
~Can you create example REPL? It works fine for me~ Okay I can see it now
