### ISSUE TITLE
Incomplete object is returned

### ISSUE THREAD

**Issue by andreasnuesslein** [mskocik/svelecte#104]
I have the following situation

```svelte
            <Svelecte
              bind:value={project}
              options={projects}
              on:change={onSelectProject}
              valueAsObject={true}
              clearable={true}
              multiple={false}
              required={true}
            />
```

where `projects` is a long list of complex objects, with various "sub-objects".

For _some_ reason, upon selecting an item, not the complete item is set in the `project` (`bind:value`). 

If I implement this with native `select`, I do get the whole object.

```svelte
      <select bind:value={shipment.project} on:change={onSelectProject} required>
        {#each projects as project}
          <option value={project}>
            {project.name}
          </option>
        {/each}
      </select>
```

I know this is rather nebulous and sadly I can not reveal any screenshots or similar. :S

Either way, I felt like I should report because I generally really like this project here :heart:

**Comment by mskocik** [comment]
Can you reproduce it in REPL in some form?

**Comment by andreasnuesslein** [comment]
actually yes, creating a REPL also revealed the problem:

https://svelte.dev/repl/f2a4591d4e334059a307838bc768fe5b?version=3.47.0

as you can see: it will infer all the objects' fields from the first list entry. 
I'm not 100% certain but I'm assuming that this happened in my code too.

**Comment by mskocik** [comment]
The current behaviour is intentional, because properties are extracted from first option item. Of course the expectation was, that all options are in same format. When you swap those items, then everything works correctly.

But definitely this could be improved.

**Comment by mskocik** [comment]
Can you reproduce it in REPL in some form?

**Comment by andreasnuesslein** [comment]
> Can you reproduce it in REPL in some form?

well I had a REPL a while back, but are you asking: "is it fixed now?" - i think it is.
I'm not actually using your component to be honest, so I can't say for certain.

cheers

**Comment by mskocik** [comment]
I think this must have been some internal GitHub issue, because I haven't sent this mail today (I sent it in April 😃)
