### ISSUE TITLE
[Firefox] Pressing `Tab` doesn't always focus next input

### ISSUE THREAD

**Issue by mskocik** [mskocik/svelecte#109]
When having long dropdown (with scrollbar), pressing `Tab` with `selectOnTab=false` (default), tabbing out with opened dropdown focuses body and on next `tab` press focus next input. 
[REPL](https://svelte.dev/repl/179fcd5b70864e26b85af3183d68db9e?version=3.48.0)

**Comment by wylfen** [comment]
I seem to be hitting this bug still. When tabbing out with an opened dropdown, some invisible element is focused and on the next tab focus returns to the first element of the entire document. It's only possible to tab along multiple elements if the dropdown is first dismissed with Enter (or, in the case of `multiple=false`, by selecting an element).
