### ISSUE TITLE
Add options groupLabelField and groupValueField

### ISSUE THREAD

**Issue by g012** [mskocik/svelecte#110]
Similar to valueField and labelField, it would spare us a conversion if we had groupLabelField and groupValueField for group headers.
Thanks !

**Comment by mskocik** [comment]
Yes, can be definitely added to the configuration. Feel free to contribute. Basically it's needed only in `list.js` when converting `options` to flat list. (I'm writing it from my memory, maybe I am not 100% right)

**Comment by g012** [comment]
Thanks :)
