### ISSUE TITLE
readSelection does not return whole object ?

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#111]
Hi, the `readSelection` seems to not return the whole passed object as is stated in the docs.

I have array of categories
```json
[
  {
    "id": 2,
    "name": "Kategorie A",
    "multipleAllowed": false,
    "children": [],
    "parts": [],
    "rootId": 1,
    "rootName": "Čalounění",
    "root": {
      "id": 1,
      "name": "Čalounění"
    }
  },
  {
    "id": 3,
    "name": "Kategorie A",
    "multipleAllowed": false,
    "children": [],
    "parts": [],
    "rootId": 1,
    "rootName": "Čalounění",
    "root": {
      "id": 1,
      "name": "Čalounění"
    }
  }
]
```
setup as this
```svelte
  <Svelecte
        searchable={false}
        options={category.children}
        inputId="sp-cat-{category.id}"
        bind:readSelection={selectedCategory}
        bind:value={selectedCategoryId}
        on:change={handleCategorySelect}
        placeholder="Vyberte kategorii"
/>
```
Sometimes the read selection returns just a option like object 
```json
{
  "id": 2,
  "name": "Kategorie A"
}
```
instead of a whole thing

Am I missing something ?

This happens only the second time the svelecte component is initialized/updated. I did check the passed options prop and it's fine

**Comment by mskocik** [comment]
Are you using the latest version? If yes, can you setup reproducible example in REPL? It works fine for me when I am trying this.

**Comment by mskocik** [comment]
Can you at least share how your svelecte markup looks like?

**Comment by FluffyDiscord** [comment]
I have rewrote the logic so that I don't use `readSelection` at all, since I had to finish my project. This can be probably closed... The behavior is weird and hard to isolate.

**Comment by tom-asmblr** [comment]
Apologies for my message @mskocik - the issue was found upstream of the component through a series of binds.

**Comment by mskocik** [comment]
@tom-acceleratecompliance thanks for clarifying your case. 

Anyway I will keep this open as potential bug.

**Comment by mskocik** [comment]
Most probably fixed in v4, which has just been released. Re-open if you would know how to reproduce it
