### ISSUE TITLE
Ability to trigger re-fetch

### ISSUE THREAD

**Issue by tom-asmblr** [mskocik/svelecte#113]
Hi, thanks for a fantastic library.
I've looked through the docs and the source code, but struggling to find a way to do this.
I've got situations where I know the data for the dropdown has changed and I'd like to trigger a re-fetch, but there doesn't seem to be a way to do it in the API.

I've tried resetting the fetch prop on the component, which does work, but causes a set of strange side-effects with the value. Ideal use-case would be in the value of the dropdown in not in the return set of new options, it either removes the value.

Thanks

**Comment by mskocik** [comment]
How does your svelecte component look like?

**Comment by tom-asmblr** [comment]
Hi Martin
This is what I'm hoping to achive:

```svelte
<script>
  import Svelecte from 'svelecte'
  export let value

  let dropdown

  function fetchItems() {
    return new Promise((resolve) => {
      // Network call here
      resolve(res.items)
    })
  }

  // This is called externally when a data change occurs which will change
  // the result of the network call.
  export function dataChanged() {
    // Trigger a new call to fetchItems, updating the dropdown options
    // If the existing value does not match any of the new options, it will be cleared
    dropdown.refetch() 
  }
</script>

<Svelecte 
  fetch={fetchItems}
  fetchMode="init"
  bind:value
  bind:this={dropdown}
/>
```

Please let me know if you need more information or if there is an easier way to achieve this.

Thanks

**Comment by mskocik** [comment]
Hopefully the fix solves your issue. Here is my testing [REPL](https://svelte.dev/repl/a6d6f584c0b0411b8227b8e9e4d0cee8?version=3.48.0)

**Comment by tom-asmblr** [comment]
This fantastic, thanks so much @mskocik 
The only slight weirdness I can see is if the selected option is not returned in the new set of items. In that case you get a console warning and the dropdown appears blank, but the dropdown doesn't change the actual bound value. Not sure if it would be possible to update that.

Either way, this is much better for our use-case, thanks so much!

**Comment by mskocik** [comment]
Didn't catch that during testing, will fix today

**Comment by mskocik** [comment]
@tom-acceleratecompliance are you sure about this? My REPL (posted above) resets also bound value. Can you provide example, when it is not working?

**Comment by tom-asmblr** [comment]
Hey @mskocik - sorry you are right, it does look like value of the dropdown changes.

We didn't pick it up because we drive some behaviour off the `on:change` event, which does not fire when the value changes to undefined due to the option no longer being in the list. Do you think we should fire that event when this occurs?

Also, it looks like we get the following warning, which may be intended:

<img width="554" alt="image" src="https://user-images.githubusercontent.com/67450961/176668669-0a1dfafc-4690-46e4-91bf-d51fad2547ea.png">

**Comment by mskocik** [comment]
> Do you think we should fire that event when this occurs?

Definitely not. Because that would/could potentially result in multiple `on:change` trigger under different circumstances.

But it is possible to add specific event for this use-case. Would that be helpfull to you? For example called `on:invalidValue`

> it looks like we get the following warning, which may be intended:

And yes the warning is intentional, because sometimes user could wonder, why the value is reset to `null` (Svelecte auto-check for valid/invalid `value` provided)

**Comment by tom-asmblr** [comment]
Hi @mskocik - thanks for the great response, that all makes sense.
The `on:invalidValue` would be hugely helpful for us and would clean up a fairly messy workaround in our case, but also understand it might be quite niche so don't worry about it if it will add complexity.

Thanks again for your help and the fantastic library!

**Comment by mskocik** [comment]
Event added, let me know if it's helpful :)

**Comment by tom-asmblr** [comment]
This works perfectly, thanks!

**Comment by tom-asmblr** [comment]
Hello Martin, apologies to ping you on this issue again.

We've found an issue when using `valueAsObject=true`. When the dropdown values change, `invalidValue` isn't called and the value is not set to nil.

Let me know if you need more information or a repl.

Thanks

**Comment by mskocik** [comment]
Hi Tom, REPL would be great.

**Comment by tom-asmblr** [comment]
Hi Martin,
Please see the repl:
https://svelte.dev/repl/fca819be72ec4850a584776cbeb49709?version=3.49.0

With `valueAsObject=true`
1. Open dropdown, click 'Foo'
2. Click 'Change to bar'
3. Loading indicator can be seen on dropdown, but "Value" stays as { "label": "Foo" }.
4. Clicking on the dropdown shows the new option, "Bar", but no invalidValue event is thrown and the value of is not changed.

With `valueAsObject=false` - working as expected.
1. Open dropdown, click 'Foo'
2. Click 'Change to bar'
3. Loading indicator can be seen on dropdown, Value is reset to nothing.
4. Clicking on the dropdown shows the new option, "Bar", the value is reset and the invalidValue event is throw

**Comment by mskocik** [comment]
Should be fixed in new version 😎

**Comment by tom-asmblr** [comment]
This works perfectly, thanks @mskocik !

**Comment by macsupport** [comment]
I was looking for a possible way to _refetch_ when I found this thread. Unfortunately, all the links to REPL's are invalid so following it was difficult. My question is if there is a way to refetch items programmatically? I am using Svelecte with an API but I also combine user added items that are stored in Firestore. I combine my API and Firebase items to be searched with Svelecte.
 I have been able to get Svelecte to work with this "hack" but when one adds or deletes an added item, I need a way to refetch to update the dropdown. 
 Thanks for your great project!!

**Comment by mskocik** [comment]
There is none, but you could update your `fetch` property to trigger refetch when you add/remove option.

**Comment by macsupport** [comment]
Thanks. Just so I can understand, are you referencing `refetchWith(newValue)` or that I would add a callback to do a `refetch` when I add or delete an added item?

I use fetch="https://vet-drugs.vetcalculators.workers.dev"  rather than fetch="https://vet-drugs.vetcalculators.workers.dev/url?search[query]", so i didn't try refetchWith. In addition it would have a `newValue = ' '`

**Comment by mskocik** [comment]
> Thanks. Just so I can understand, are you referencing `refetchWith(newValue)` or that I would add a callback to do a `refetch` when I add or delete an added item?

Not really, I meant something like [this](https://svelte.dev/playground/hello-world?version=5.16.0#H4sIAAAAAAAACm2QwUrEMBCGX2UIC9uCtPduqwgiHjyteLLCpumUjaZJTKa7Sum7O91WvXhL_nzfz0xGYWWPohAPaIyDswumhQRbTdim4kp02mAUxcso6MvP3Bxwvlq33mfxhIbmrJER_8uVs4SWuEaUUQXt6bq2Neneu0DwxBgqQuiC62Eb1-t2xwxTLEeC5_0jVLA9EvlY5PlbdNYbqfDoTIsh49m0ci1myvW5NM3Qx4tPBgk6JHVkexNJEiZcle5gKe8Gq0g7CwEvVJLCOOf8skqHzcjCdPMRq814x35m3TlJp8OMTbUt87-NbNkMRNzmrDJavVfjWjtd75dDmS8E0-Xv3uPCgJENmnuNpq1qQZpnrwWcpBnwJ9QtJ5Czzb9K-EmioDDg9Dp9A4lysgHHAQAA)
