### ISSUE TITLE
Local collapsedSelection localization reflects global option

### ISSUE THREAD

**Issue by gthomas3** [mskocik/svelecte#114]
Thank you for your work on this package! I've just begun integrating into a project and noticed the local option for overriding the collapsedSelection i18n localization is not working as expected. Please advise if I'm implementing the API incorrectly.

Code to reproduce:

```
<script>
  import Svelecte, { config } from "svelecte";

 const customLocalization = {
    collapsedSelection: (count) => `${count} customers  selected`,
 };
</script>

<Svelecte
  multiple
  collapseSelection
  selectOnTab
  placeholder=""
  i18n={customLocalization}
  options={customers}
  bind:value={selectedCustomers}
  on:change={handleCustomerSelection}
/>
```

Expected outcome: Once a selection is made "n customers selected" is displayed
Actual outcome: Once a selection is made "n selected" is displayed

I tested the global override option using the code below, which displays "n customers selected" as expected.
```
config.i18n = {
   collapsedSelection: (count) => `${count} customers  selected`,
}
```

**Comment by mskocik** [comment]
Thanks for reporting. I've never customized it personally, so I haven't caught the bug myself :)
