### ISSUE TITLE
Allow multiple without valueAsObject

### ISSUE THREAD

**Issue by gthomas3** [mskocik/svelecte#115]
Not sure if I'm implementing this incorrect, but is it possible to use `multiple` without `valueAsObject`?

What I'm trying to do is pass `options` an array of objects, but bind `value` to an array of only the `value` parameters.

```
const selectedFruit = ["APPLE", "GRAPE"]

<Svelecte
multiple
options={ [{text: "Apple!", value: "APPLE"}, {text: "Grape!", value: "GRAPE"}, {text: "Kiwi!", value: "KIWI"}] }
bind:value={selectedFruit}
/>
```

For me this hasn't worked, and I've needed to pass `valueAsObject`, and updated `selectedFruit` to an array of objects instead of an array of strings.

Thanks!

**Comment by mskocik** [comment]
What about this one? [REPL](https://svelte.dev/repl/0177b17b75384d78a8315fbc3afea908?version=3.49.0)

**Comment by mskocik** [comment]
Also when you do not specify `valueField` and `labelField`, it's best to write property representing value as the first one.

**Comment by gthomas3** [comment]
Ah, there's a slight difference between the example above and my code. I was initializing `selectedFruit` as an empty array, and then populating it in an onMount function, like this:

```
const selectedFruit = []

const handleComponentMount = () => {
  selectedFruit = parseFruitData($fruitDataStore)
}

onMount(handleComponentMount)
```

When you do that, Svelecte doesn't display the selected fruit on page load, but if you skip the onMount call, and set selectedFruit directly like this, it works:

```
const selectedFruit = parseFruitData($fruitDataStore)
```

Awesome..

Thanks for your quick response, appreciate it!

**Comment by mskocik** [comment]
I don't know. Even your example works :)

```
<script>
	import { onMount } from 'svelte';
	import { writable } from 'svelte/store';
	import Svelecte from 'svelecte';
	
	// 👇 must be "let", not "const"
  let selectedFruit = [];	
	
	const store = writable(["APPLE","KIWI"]);
	
	const parse = (store) => store;

	const handleComponentMount = () => {
		selectedFruit = parse($store)
	}

	onMount(handleComponentMount); 
</script>

Selected: <code>{$store}</code>
<Svelecte
valueField="value"
labelField="text"
multiple
options={ [{text: "Apple!", value: "APPLE"}, {text: "Grape!", value: "GRAPE"}, {text: "Kiwi!", value: "KIWI"}] }
bind:value={selectedFruit}
/>
```

**Comment by turkic-dev** [comment]
Hey I have this problem in all browsers. Can you help me?I can only create one. Others are not visible at all.

```
<script>
	import Svelecte from 'svelecte';
	const list = [{ id: 1, name: 'Item 1' }, { id: 2, name: 'Item 2'}];

</script>

<Svelecte options={list} multiple creatable={true} clearable={true} searchable={true}></Svelecte>
```
