### ISSUE TITLE
fetch= with Promise?

### ISSUE THREAD

**Issue by MarkBFamFour** [mskocik/svelecte#117]
Hi,

I am writing and application in which I want to use Svelecte for a searchable drop-down for a large database accesses via a REST API, but instead of fetching using a direct URL I want to use a method that returns a ```Promise<Array<Options>>``` type return which is suitable for the options of Svelecte. What its the best way to do this? Can the component handle this already or will I have to put a method in to do something like refresh the ```{options}``` attribute on every keypress?

Thanks.

**Comment by mskocik** [comment]
Check this [REPL](https://svelte.dev/repl/175dd2e918d94e5fb1f093f4fa717f79?version=3.49.0) example using custom `fetch` function, which returns promise. Is it clear enough for you?

**Comment by MarkBFamFour** [comment]
Thanks, that worked perfectly. I think I may have needed to update the package, as it just took in my Promise output straight off the bat, but thanks for the assist! :)

There may be value to adding an example like this to the docs, too (unless it's there and I'm just blind), for folks using stuff like Axios for API calls it's really useful to know.

**Comment by mskocik** [comment]
@MarkBFamFour yes, you are definitely right. Documentation could be improved. I don't have time for it at the moment. And it would take a lot of time to rework docs completely, which I would like to do some day. I already have opened issue for it (#49). So if you have other suggestions, what could be improved, add it there.

**Comment by maxkozlowski** [comment]
It looks like the proposed solution doesn't work with the new SvelteKit version. What would be the best way to do it for the new release? Thanks!

**Comment by mskocik** [comment]
Can you provide minimal repo for reproduction? Would save me some time. 
But I am not sure why it should be broken now.

**Comment by maxkozlowski** [comment]
Hello! Ah, apologies for this - there was just something on my end that didn't work in the end, but the proposed solution does work with the new Sveltekit release. I deleted the comment to avoid confusion, but somehow it must have been still visible to you! Sorry for this.
