### ISSUE TITLE
Reroute based on value selected

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#118]
Hello!

Thank you for your awesome library, it's super useful.

What would be the best way to reroute based on value selected? For example if a user selects in search "productA", you would want to send them to domain.com/productA.

The main question is around what event I should use to know that user selected a product? (for rerouting itself I could probably use `goto()`)
I've tried `on:change` - but it looks like it fires immediately when the website is loaded :thinking:.

Thanks!

**Comment by mskocik** [comment]
You want to use `on:change`. But if it's fired immediately, it means, that value has been changed. Demo REPL would be useful.

**Comment by maxkozlowski** [comment]
Thank you! See [REPL](https://svelte.dev/repl/660561153a9045d388dfcaa4d7bf8fc7?version=3.49.0).

**Comment by mskocik** [comment]
The problem in your example is that you are immediately calling `toggle()`. But in fact you want just to bind it to the `change` event:

```svelte
<Svelecte on:change={toggle}>
// instead of
<Svelecte on:change={toggle()}>

// this also works
<Svelecte on:change={e => toggle()}>
```

Here you have correct version: [REPL](https://svelte.dev/repl/d0885b207c2947bcaa4964c744482b56?version=3.49.0)

**Comment by maxkozlowski** [comment]
Ah I see where my mistake was. Thank you for explaining it!

For anyone trying to find how to reroute your Svelecte, see below. Hope it helps.

```
<script>
    import Svelecte from "svelecte";
    import { goto } from "$app/navigation";

    let value;

    function routeToPage() {
            goto(`/url_suffix/`+value);
    }
</script>

<Svelecte bind:value on:change={routeToPage} />
```
