### ISSUE TITLE
setSelection does not seem to work

### ISSUE THREAD

**Issue by PlkMarudny** [mskocik/svelecte#120]
Not sure if understood setSelection() API method properly, but is it supposed to set the selection programmatically? If yes, it does not  seem to do so - [REPL](https://svelte.dev/repl/fc74430f627749e8a0be69eebe3d2bbd?version=3.44.2) here - bound values are objects.

**Comment by mskocik** [comment]
Methods `getSelection` and `setSelection` are required only for custom element. They are "internal" and they shouldn't be listed in Public API section.

In your example you can change bound value directly, no need to use this api method.

**Comment by PlkMarudny** [comment]
Somehow I am doing sth wrong, another [REPL](https://svelte.dev/repl/3997c99c63af4953b85c0d4f58a935b0?version=3.44.2) with a direct assignment to the bound value; does not seem to work.

**Comment by mskocik** [comment]
Yes, you're doing it wrong, because you are using `labelAsValue`, but this property is designed to be used with plain arrays only. Behavior in conjunction with `valueAsObject` is undefined. 

Line from documentation:

> For plain array options you can also specify if you are interested in `value` (default) or `label` property by setting `labelAsValue` property to `true`.

By plain array I mean this:
```javascript
const options = ['One', 'Two' 'Three'];
```

Is it clear now?

**Comment by PlkMarudny** [comment]
Yes, it is, thank you.

**Comment by mskocik** [comment]
Just comment for myself - be more clear about this when doing #49

**Comment by mskocik** [comment]
@PlkMarudny maybe you were confused because you just wanted to show `label` property as option visible "label". Svelecte is trying its' best to automate this for you and to pick correct _"value"_ and _"label"_ properties. In case you have option objects with multiple properties, you can specify the one being shown by `labelField`

**Comment by PlkMarudny** [comment]
I just want to set the value programmatically when valueAsObject={true}
