### ISSUE TITLE
[Request] Add is-empty and is-invalid classes

### ISSUE THREAD

**Issue by Bandit** [mskocik/svelecte#121]
Unless I'm missing something obvious, there's no easy way to style invalid or empty fields (or perform validation in general).

If I mark a `Svelecte` element as `required` it should visually show that a blank value is invalid. This could be achieved like so (pseudocode):

`if (selectField.is(":invalid")) parent.classList.add("is-invalid")` (and similar for `is-empty`)

That way people can reasonably rely on [form.checkValidity()](https://developer.mozilla.org/en-US/docs/Learn/Forms/Form_validation#validating_forms_using_javascript) for client-side validation. Also easier to add custom style overrides for the different states.

**Comment by mskocik** [comment]
I am not really convinced about it. This can be achieved on your side like in this [REPL](https://svelte.dev/repl/9e46405ad37c49cf9db75f5c4df04878?version=3.50.0)

You can always determine the validity state based on bound value property. And you can rely on `checkValidity` for internal `<select>` element.

Personally I've never had need for this and I am also using its custom element version in PHP apps. 
![image](https://user-images.githubusercontent.com/25513620/189088251-5eecdcc7-ce1a-42aa-bdb2-ea67f7bd8a42.png)

But you need to convince me, or prepare PR yourself.

**Comment by Bandit** [comment]
The `:has(select:invalid)` is a clever idea, I hadn't thought of that.

Can I ask why the above REPL isn't linked somewhere clearly in the documentation? There's almost zero information about validation and how to do it - which I personally find very surprising for a form element replacement.

Whether or not you add quick/convenience ways to determine validation is up to you - but in my opinion a drop-in form field replacement should integrate nicely with existing standards such as `checkValidity()`

For now I'll use the `:has(select:invalid)` method, thanks. Recommend adding this to the docs.

**Comment by mskocik** [comment]
Don't forget that even thouh Firefox supports :has, it isn't enabled yet 
by default.

I created this REPL for you. There is one REPL related to validation 
mentioned in github readme, but it's missing in doc site. I must have 
missed it.

I know that docs need rewrite, but it's so hard to write it the way, it 
will be really clear for everybody else and it's more time consuming. 
And I don't have time for it right now.

**Comment by Bandit** [comment]
Maybe just something like this:

```html
<h2>Validation</h2>
<p>I intend to rewrite this documentation at some stage, but until then here are two REPLs that may help.</p>
<ul>
  <li>[REPL1]</li>
  <li>[REPL2]</li>
</ul>
```
