### ISSUE TITLE
Current and currentTarget always return null

### ISSUE THREAD

**Issue by azizelmadini** [mskocik/svelecte#123]
Hello guys,

I'm trying to get the event target of the select on the change event to use for validation with svelte-forms-lib and yup, but i get the target in the CustomEvent always null, any help if i'm missing an option or something, and Thanks for this amazing Select.

**Comment by mskocik** [comment]
CustomEvent has only `detail` property defined, which represents value, 
not element itself. Provide REPL which is not working and I can show the 
workaround.

**Comment by azizelmadini** [comment]
This is an example :
`<script>
import Svelecte from 'svelecte';
import { createForm } from "svelte-forms-lib";
import * as yup from "yup";
	
const list = ["Item 1","Item 2","Item 3","Item 3"]; 
let selectValue=""

const { form, errors, state, handleChange, handleSubmit } = createForm({
	initialValues: {
		selectValue,
	},
	validationSchema: yup.object().shape({
		selectValue: yup.string().oneOf(list, "select an option"),
	}),
	onSubmit: (values) => {
		console.log(values.selectValue)
	},
});

</script>
<form on:submit={handleSubmit}>			
	<select on:change={handleChange} bind:value={$form.selectValue}>
		{#each list as item}
			<option value={item}>{item}</option>
		{/each}
	</select>
	<button>submit</button>
</form>
{#if $errors.selectValue}
	<p style="color:red">{$errors.selectValue}</p>
{/if}`

**Comment by azizelmadini** [comment]
This is an example : 
```
<script>
import Svelecte from 'svelecte';
import { createForm } from "svelte-forms-lib";
import * as yup from "yup";
	
const list = ["Item 1","Item 2","Item 3","Item 3"]; 
let selectValue=""

const { form, errors, state, handleChange, handleSubmit } = createForm({
  initialValues: {
    selectValue,
  },
  validationSchema: yup.object().shape({
    selectValue: yup.string().oneOf(list, "select an option"),
  }),
  onSubmit: (values) => {
    console.log(values.selectValue)
  },
});
</script>
<form on:submit={handleSubmit}>
  <Svelecte options={list} on:change={handleChange} bind:value={$form.selectValue}></Svelecte>	
  <button>submit</button>
</form>
{#if $errors.selectValue}
  <p style="color:red">{$errors.selectValue}</p>
{/if}
```

**Comment by mskocik** [comment]
Svelecte supports `validatorAction` property, which is designed to be hooked to the underlying `<select>` element as an action.

Your given example doesn't work in svelte REPL, so I can't provide with the working example. But basically you need to do this:

```svelte
function myAction(node) {
  node.onchange = handleChange;
}

<Svelecte validatorAction={[myAction]}></Svelecte>
```

**Comment by mskocik** [comment]
I've just added `change` event in the `3.9.6` version, previously there was only `input` event to hook your handler to.

**Comment by azizelmadini** [comment]
I could not make it work that way too, so i had to drop `onchange` and use just `onsubmit` for validation, because in somehow `onsubmit` validate the value not the element itself.
Thanks for help.

**Comment by mskocik** [comment]
Check how I did it here [REPL](https://svelte.dev/repl/9b1ecd086e86439fa2fbebfb70f792a4?version=3.50.1). I had to copy-paste required logic from svelte-forms-lib and replace `validationSchema` by `validate` prop to make it work. (IMHO I wouldn't use this validation lib, because even examples on their page don't really work).

But I think the result behavior is what one would expect.
