### ISSUE TITLE
Doc request: dnd examples

### ISSUE THREAD

**Issue by dsm054** [mskocik/svelecte#126]
Often drag and drop is only needed to rearrange _within_ a selection, not between selections.  Selecting columns to format an output, for example, which is my current problem.

Unfortunately I keep bouncing when attempting to combine the svelecte dnd example with the svelte-dnd-action multiple dndzone example, especially when trying to work with groups.

Could we add examples of the recommended pattern for having multiple dndzone types for both the non-group and the group cases?  This would align with the goals of #49, I think.

**Comment by mskocik** [comment]
I am not sure I understand what is your problem. Can you describe it more? 

But in general I am not sure it will be possible, because dnd integration was meant for simple selection rearrangement

**Comment by dsm054** [comment]
Sure!  What I mean is that if you naively put a few svelecte selectors using dndzone next to each other, you can drag and drop between all of the selections.  So if I have one with colours and one with sizes, I can carry the "red" from the first zone and slot it into the sizes beside "large".  That's not what I want: all I need is rearrangement within the list, which I'd have thought would be easier. :)

If I understand the way svelte-dnd-action is supposed to work, we're supposed to use the type parameter, as here: `https://svelte.dev/repl/4d23eb3b9e184b90b58f0867010ad258?version=3.22.3`, but so far I can't get it to work together with svelecte.  If the example linked in the docs could be extended to have two separate and functionally independent entries, that would solve my problem and maybe help other people too.

**Comment by mskocik** [comment]
Okay, it was bug, which allowed dragging across svelecte instances. It's fixed now and behave correctly by default. (You can "enable" this cross-sharing behavior againg by specifying the same `inputId` prop as shown in example).

And I agree, dnd should be mentioned directly in the new docs.
