### ISSUE TITLE
Options with simple array

### ISSUE THREAD

**Issue by webfrank** [mskocik/svelecte#127]
Hi,
  great work!

One question, if I use a simple array for options like: ['One', 'Two'] the bind:value will be the array index.

Is it possible to return the value from the array and also select the correct item if value is set to one of the array values?

**Comment by mskocik** [comment]
You probably want to use property `labelAsValue`?

**Comment by webfrank** [comment]
Thank you, missed the option, exactly what was searching for.

**Comment by webfrank** [comment]
Sorry to bother, but if I use multiple="true" and simple array it doesn't work.

This is my test-case:

```
<script>
import Svelecte from 'svelecte';

let value, selectedItems;

$: console.log(value)
$: console.log(selectedItems)
</script>

<Svelecte
    multiple
    fetch='/api/rule/ports/tags'
    labelAsValue
    bind:value
    bind:readSelection={selectedItems}
    on:fetch={(data) => console.log(data)}
/>
```

The service returns an array like: ['iot', 'poe'] but the select only shows 'o' (I presume from object Object)

**Comment by mskocik** [comment]
Svelecte uses objects internally (it internally converts simple array to object array), so you need to convert result array to object array. Like in this [REPL](https://svelte.dev/repl/1ae85f35c31d46e5833a09f135278c62)

**Comment by webfrank** [comment]
Hi, if multiple is true it seems it doesn't convert to object array like for multiple = false.

If I send the data like [{tag: 'iot'},{tag: 'poe'}] it works. I expect to handle the fetch data in the same way like multiple false:

['iot','poe'] -> [{option:'iot', value: 0},{option: 'poe', value: 1}]

which works.

**Comment by mskocik** [comment]
Maybe I wasn't clear enough when I said, that plain array is converted to objects internally. This happens ONLY with initial `options` property.

If you use remote fetching and need to transform received value to object array, you need to define your own `fetchCallback` as I showed in REPL in my last comment. Where I tried to mimic your demo, just replaced your API endpoint by "synthetic" fetch.

Maybe we're just talking about 2 different things and in that case I would need more explanation or demo REPL which we can talk about.
