### ISSUE TITLE
Fire an event on empty dropdown

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#130]
For tracking purposes I might need to fire a function when user gets empty dropdown. I've search through the docs but couldn't find anything that I could use 🤔  Would anyone be able to help?

**Comment by mskocik** [comment]
Try to hook the mutation observer for the dropdown and them check if it has only one options saying "no options". There is nothing in thw library that could be used for your use case

**Comment by mskocik** [comment]
You mean use case, when user search for something, but no options are 
matching?
