### ISSUE TITLE
Prefetch possibilities

### ISSUE THREAD

**Issue by RykGitProjects** [mskocik/svelecte#132]
Hello,

I am using your library in my project. It's great!

Currently I am trying to get [prefetch ](https://kit.svelte.dev/docs/link-options) to work. I found the solution - in search results (in +server.js file) I changed values which are shown in search results by adding them <a href=<where to go>Text searched</a>

And it works this way!

It just doesn't seem to be proper solution

I wonder if there might be a better solution for this?

Kind regards,
Richard

**Comment by mskocik** [comment]
I am not sure I understand what's the issue.

Do you have searchable svelecte with defined `fetch` property, but you 
want some initial result set defined? Or is it something else? Can you 
describe it more?

**Comment by RykGitProjects** [comment]
Sure

Currently:
1)User types something into search
2)There is response and search shows possible results (which match what user typed)
3)User hovers over specific result which interests him
4)User click specific results
5)User is redirected to specific page (which he clicked)

I would like in point 3 to already fetch the page which is hovered. So step 5 will be much smoother from user perspective

**Comment by mskocik** [comment]
You could try to create your own Item component and intercept the `hover` event there. Check the REPL how to do custom items here: https://github.com/mskocik/svelecte#custom-items

But maybe the way you are handling it right is just fine :)

**Comment by RykGitProjects** [comment]
Thanks for your reply!
Used concat with a href. It works, sor for now it is good :)
