### ISSUE TITLE
Mobile - changing input (inside text)

### ISSUE THREAD

**Issue by RykGitProjects** [mskocik/svelecte#134]
Hi!

I am experiencing UX flow (?) that on mobile when I put keyword with error (for example alania), and tap in between any letters (for example la) it does only focus (on alreacy focues) search bar instead of moving coursor into that area, so I would be able to change it to albania. Video of the case:

https://user-images.githubusercontent.com/95529851/196200222-d9e20dcc-fc5e-4466-9d6a-f19938bd62c0.mp4

Is there a way to overcome it ?

Kind regars,
Richard

**Comment by mskocik** [comment]
This was meant to be intentional - to be able to open dropdown by clicking on it. But this case should behave as expected.

_Note for myself: it's not relevant only to mobile_
