### ISSUE TITLE
Custom Button with custom function as first option

### ISSUE THREAD

**Issue by blazzjosh** [mskocik/svelecte#140]
How may this be achieved? - not necessarily using just createable.

I want to lead user to a drawer or another form to properly create a new option for svelecte.

<img width="200" alt="Screenshot 2022-11-22 at 6 04 01 AM" src="https://user-images.githubusercontent.com/19534082/203226478-f0c57a25-0e45-4784-a85a-a8f1398aa4b0.png">
<img width="241" alt="Screenshot 2022-11-22 at 6 03 25 AM" src="https://user-images.githubusercontent.com/19534082/203226479-e8800ab3-5893-46b7-827e-fbc2c791e866.png">

**Comment by mskocik** [comment]
Svelecte is not designed to be this customizable. Although it is possible to do it. Quick example [here](https://svelte.dev/repl/6e59b1b4d99040149bce231c5c1a65b4?version=3.53.1).

**Comment by blazzjosh** [comment]
is it possible to add custom function to `createable` ?

or better still - after searching through `options` with `no matches found`... the above Add New button returns alongside the `no matches found` message.

**Comment by mskocik** [comment]
Not exactly the same, but you could potentionally use `control-end` slot for it, which was added in the latest version.
https://github.com/mskocik/svelecte#customizable-slots
