### ISSUE TITLE
Refactor css to allow to pass inline CSS variables

### ISSUE THREAD

**Issue by mskocik** [mskocik/svelecte#141]
Hi is it still expected to use `global` for basic styling? Passing a CSS variable to the component (`<Svelecte --sv-min-height="35px" />`) does not work since it is wrapped in extra markup . It also get overriden for any element that isn't the root `.svelecte-control` since the CSS variables are reapplied for each sub-element, example with 

```
<style>
	:global(.svelecte-control) {
		--sv-min-height: 32px ;
	}
</style>
```

**CSS variable is applied for top-level element:**

![image](https://user-images.githubusercontent.com/27226185/203777052-93c9a535-9452-4b81-8cc7-b20c8098fe05.png)

**But default comes back for any nested element:**

![image](https://user-images.githubusercontent.com/27226185/203776932-3c6fd916-9db1-4e62-91c8-c784c679dcb2.png)

_Originally posted by @gterras in https://github.com/mskocik/svelecte/issues/98#issuecomment-1326331763_

**Comment by noname-oni** [comment]
Really needed a feature. Especially with tailwind, I can't easily figure out how to customize the selector -_-

**Comment by Neptunium1129** [comment]
Is there any progress in this work?
I don't know whose idea 38px is.

**Comment by mskocik** [comment]
Feel free to contribute, by code or financially. My time is limited, so focusing more on high priority tasks.

I am planning to implement it myself in v4, which will be... when it will be. No sooner nor later.

**Comment by gterras** [comment]
By the way this can easily be overridden using CSS `specificity`.
