### ISSUE TITLE
Bug: Setting initial value is not reflected

### ISSUE THREAD

**Issue by ajmeese7** [mskocik/svelecte#142]
Whenever I do something like the following the value remains blank and nothing is selected in the element:

```js
<Svelecte
	options={realmsData}
	bind:readSelection={selectedRealm}
	inputId="realm"
	placeholder="Realm"
	value={nodeData.realm || ""}
/>
```

I am 100% sure that `nodeData.realm` has a value that is one of the values from the list of options.

**Comment by mskocik** [comment]
Can you create REPL with the issue?

**Comment by ajmeese7** [comment]
Turns out I was trying to pass the `label` option as the value, not the actual option. Using the following code solved it:

```js
<script>
  let initialRealm = realmsData.find((realm) => realm.label === nodeData.realm);
</script>

<Svelecte
  value={initialRealm.value || ""}
/>
```

Sorry for the confusion on my part, cheers!

**Comment by mskocik** [comment]
Great to hear that, thanks!
