### ISSUE TITLE
Fetch and multiple return "provided value property is invalid"

### ISSUE THREAD

**Issue by LukasGur** [mskocik/svelecte#146]
When I am fetch new data from server and select value. Svelecte push warning error that provided value is invalid.

When I am not fetch new values, only select some items. It's everything ok.

```js
<Svelecte
        fetch={getNewProductValues}
        multiple
        disableSifter
        options={products.map((product) => ({
          label: `${product.name} - ${product.id}`,
          value: product.id,
        }))}
        on:change={(e) => {
          $form.article_collection = e.detail.map((a) => a.value)
          updateTouched('article_collection', true)
          validateField('article_collection')
        }}
        value={$form.article_collection}
/>
```

**Svelecte.svelte:383**
<img width="553" alt="image" src="https://user-images.githubusercontent.com/68665726/212887050-cdb618fd-6b14-43a3-997c-7c25c95efd7a.png">

**Comment by mskocik** [comment]
Svelecte behaviour _should_ be correct (although there were updates in 
this area lately). I would need to see REPL with replicable issue.

**Comment by LukasGur** [comment]
Repository with repeated error
https://github.com/LukasGur/svelecte-issue/blob/master/src/routes/%2Bpage.svelte

**Comment by mskocik** [comment]
I don't understand why not just simple REPL, when it could be copied there with no problem.

The main question is, why are you not using `bind:value={selectedValues}`? I see that weird logic even in your original example. So much manual code, when svelecte can do all for you. Like this:

```svelte
<Svelecte bind:value={$form.article_collection}/>
```

**Comment by LukasGur** [comment]
Sorry, I didn't understand what REPL means.

Because I have to call the updateTouched(), validateField() functions and I saw it as a better solution to handle it myself. However, with bind:value everything works as it should even after Fetch

Thank you

**Comment by mskocik** [comment]
I meant [svelte.dev/repl](https://svelte.dev/repl/) :)
