### ISSUE TITLE
[Refactoring] remove unnecessary `dist` file from svelecte 

### ISSUE THREAD

**Issue by tristan-f-r** [mskocik/svelecte#148]
Currently, the [dist folder is in the repository](https://github.com/mskocik/svelecte/tree/v4.0/dist). Is it a better idea (for the sake of contributions) to remove it? (If GitHub pages depends on it, it's better to use a GitHub deployment action instead).

**Comment by mskocik** [comment]
> Is it a better idea (for the sake of contributions) to remove it?

Not really. I like to have it here, when I need `iife` version for some project.

**Comment by tristan-f-r** [comment]
Wouldn't this make it annoying to resolve merge conflicts related to submitted PRs that modify source code? (Also, you can probably just publish the IIFE version to npm and use unpkg there rather than in the source control)

**Comment by mskocik** [comment]
There is no need to submit dist content in PR. When publishing package, build command is called anyway.
