### ISSUE TITLE
Border color on focus

### ISSUE THREAD

**Issue by ejkreboot** [mskocik/svelecte#149]
Thanks for the great package! I cannot seem to get rid of the faint blue border when the input has focus, for example surrounding "Select" in this screenshot:

<img src="https://user-images.githubusercontent.com/100181323/215536777-4ab14bc1-f055-42a9-8754-0beed1b00224.png" 
 width=50%>

I have tried:
```
:global(.svelecte-control) {
    --sv-placeholder-color: red !important;
    --sv-active-border: 1px solid red !important;
    --sv-border-color: red !important;
    --sv-disabled-border-color: red !important;
    --sv-item-color: red !important;
    --sv-item-active-color:  red !important;
    --sv-item-active-bg: red !important;
  }
```

And:

```
.inputBox:focus {
    outline: white solid 0px !important; */
}
```

All to no avail. Any thoughts?

Here is a basic repl:

```
<script>
    import { onMount } from 'svelte';
    import Svelecte from 'svelecte';


    let categories = ["category 1", "category2"]
    let selected = null;

    function newCategory(c) {
        categories.push(c.detail.value);
    }
    onMount(() => {        
    });

</script>

<main class="container">
<h4 id="category-label">category.</h4>
<Svelecte id="category" 
            options={categories.map(e => ({label: e, value:e, $created: true}))} 
            creatable = true
            bind:value={selected}>
</Svelecte>
You have selected: {selected || categories[0]}
</main>
```

**Comment by santoshlite** [comment]
any updates on this?

**Comment by mskocik** [comment]
@ssantoshp update on what exactly? This whole "issue" was invalid in the first place, so I don't what are you refering to 🤷

**Comment by santoshlite** [comment]
@mskocik on the issue described above. What do you mean by invalid, you didn't even reply to it. Anyway I figured it out by adding:
```
.svelecte input:focus {
	  outline: none;
	  box-shadow: none;
}
```

**Comment by mskocik** [comment]
> What do you mean by invalid

It's not related to the component itself, but is introduced by additional user-provided CSS. The same applies to you - seems you define `box-shadow` for you input elements, because `outline: none` is already applied to svelecte input.

> you didn't even reply to it

I didn't have a feeling I should.

**Comment by santoshlite** [comment]
`box-shadow` here is useless i dont use it, only `outline: none` was needed because it displayed a blue outline around the input by default, i assume it's not something hardcoded by you. 

> I didn't have a feeling I should.

But now you do, interesting...

Anyways, thanks for bringing some more light on this issue
