### ISSUE TITLE
Add option to show how many items are selected instead of showing them all

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#151]
I am currently facing an issue where my select needs to be slim and can not expand vertically when selecting multiple things.

I suggest to allow showing how many items are selected if there is more than 1 item selected instead of showing them all. Selected items would also remain in the dropdown list and would be on top, so user can quickly de-select them.

How it looks:
![image](https://user-images.githubusercontent.com/10332247/219776331-388c490e-2a1a-4988-9b44-b21faf68d791.png)

How I imagine it would look like with this specific feature implemented:
![image](https://user-images.githubusercontent.com/10332247/219782342-c3757dc3-93b8-4541-b15c-f86fc0ff137a.png)

**Comment by mskocik** [comment]
You mean something like [this](https://svelte.dev/repl/95a60476757f45cebe09f85d97f3408a?version=3.55.1) with `collapseSelection` property?

**Comment by FluffyDiscord** [comment]
Kind of like that. The selected items should not be scrollable to the side, but show as mentioned, at the top of the dropdown list.

**Comment by mskocik** [comment]
Personally I don't think your suggestion is a good UX, when items jumps in the list up and down.

From technical perspective it's not possible with current implementation. Only thing, that could be updated is that `collapseSelectionFn` can return HTML string to be styled

Overflow was there just to demonstrate that ability to remove whatever items is still preserved.

**Comment by FluffyDiscord** [comment]
The dropdown list is being updated anyway whenever user selects/deselects something so the items still jump in and out of existence.

Then what about making two lists - one with all selected options, second one bellow with the rest of the options just as shown? Both would be scrollable individually. That should be actually easier to implement, since there's no need to re-sort whole option list just to put selected ones on top.

**Comment by mskocik** [comment]
But is difference between hiding selected option from the list and jumping to the start of the list.

I am planning refactoring with additional slots for v4, so this would be possible then.

**Comment by FluffyDiscord** [comment]
Any ETA on that please?

**Comment by mskocik** [comment]
Hopefully this year 🤞. I know that's not very helpful... But I don't have that much free time now.

**Comment by mskocik** [comment]
Check the updated [REPL](https://svelte.dev/repl/35a57a125ace4d41ac6428dabba0b3ca?version=3.55.1). That's basically your use case

**Comment by FluffyDiscord** [comment]
Unfortunately not, since it expands the input vertically. I can not have that. I will try making a PR today

**Comment by FluffyDiscord** [comment]
Adding link to PR https://github.com/mskocik/svelecte/pull/152
