### ISSUE TITLE
Autocomplete Suggestion List removing space between words

### ISSUE THREAD

**Issue by jbirtel** [mskocik/svelecte#153]
Hi,
I have a question/issue:
When typing in a complete word in the autocomplete field, the space between the words is removed. Maybe I can explain it better with some pictures:
![image](https://user-images.githubusercontent.com/57353201/221586651-70e4d18b-4b6b-443e-a1d2-f4608f653375.png)
![image](https://user-images.githubusercontent.com/57353201/221586484-8bbcb4a2-6edc-4aa2-8874-64ddcd4c8a75.png)

You can see that as long as I did not complete the first word in the field, the options list contains the text with space, as soon as I complete the first name, the space is removed.
I saw in your playground, that this works for your example there. So do you have an idea, how this can be fixed or what the problem is?

Cheers, 
Jonas

**Comment by mskocik** [comment]
I have no idea, without seeing your code. Create REPL with your issue at [svetle.dev/repl](https://svetle.dev/repl). Otherwise I can only guess.

**Comment by jbirtel** [comment]
Okay, I see. The problem is that I need a backend to build the autocomplete suggestions and also I am not 100% sure, what I am allowed to show of the code.

I can show you the JSONs that are coming to Svelecte as suggestions, if that helps you in anyway.

`{"data":[{"id":"60","firstName":"Jonas","lastName":"Birtel","text":"Jonas Birtel"},{"id":"73","firstName":"Jonas","lastName":"Teshome","text":"Jonas Teshome"}],"success":true,"errorCode":0,"hasValidationErrors":false,"validationErrors":[]}`
where id is the valueField and text is the labelField.


```
<div class="autocomplete-container" class:hideDropdownArrow class:hideSeparator style="width: 100%;--sv-border-radius:{borderRadius}">
    {#if label && label !== undefined && label !== ""}
        <div class="label-container">
            <span class="input-label">{label}</span>
            {#if ttText !== undefined && ttText !== ""}
                <div>
                    <Tooltip msg={ttText}/>
                </div>
            {/if}
        </div>
    {/if}
    <Svelecte bind:value bind:readSelection={selectedObject} bind:options {...autocompleteConfig} on:change style="{fontPropsStyleString || ''}
                    --sv-border: 1px solid var(--sv-border-color);
                    --sv-active-border: 1px solid var(--sv-border-color-active);
                    --sv-border-color: #D9D9D9 !important;
                    --sv-border-color-active: #58C079 !important;
                    --sv-highlight-bg: rgba(88, 192, 121, 0.3) !important;
                    --sv-placeholder-color: #9D9D9D !important;
                    --sv-bg: white;
                    --sv-item-active-bg: #F0F2F8 !important;
                    --sv-min-height: 32px;"><!-- see main.scss for the meaning, somehow the main.scss does not override the variables -->

        <div slot="icon">
            <slot name="icon"/>
        </div>
        <div slot="control-end">
            <slot name="control-end"/>
        </div>

    </Svelecte>
</div>
```

and the config is as follows

```
export function DefaultAutocompleteConfig() {
    let config: AutocompleteFieldConfig = {
        clearable: true,
        disabled: false,
        labelAsValue: false,
        multiple: false,
        placeholder: "Wähle aus...",
        selectOnTab: true,
        resetOnBlur: false,
    };
    return config;
}
export function getFormAcConfigFetch(placeholder: string, fetchKey: string, multiple = false, valueField = 'value', labelField = 'text') {
    let config = AutocompleteConfig(placeholder, valueField, labelField, multiple);
    config.fetch = "/api/" + fetchKey + "/autocomplete/svelte?qry=[query]";
    return config;
}
```

**Comment by mskocik** [comment]
Your example isn't very helpful. I can't reproduce your issue in REPL:

![image](https://user-images.githubusercontent.com/25513620/222261453-3a51c7b5-e4e4-4c1f-8c56-d2566b23093e.png)

Can't really help you until I see given issue in action.

Btw you can simulate remote fetch by similar function:
```svelte
let fetch = function(query) {
  return new Promise(resolve => {
    setTimeout(() => {				
      resolve([{"id":"60","firstName":"Jonas","lastName":"Birtel","text":"Jonas Birtel"},{"id":"73","firstName":"Jonas","lastName":"Teshome","text":"Jonas Teshome"}])
    }, 200);
  });
}

<Svelecte {fetch} />
```

**Comment by mskocik** [comment]
Hey, and what about this one? Have you solved it?
