### ISSUE TITLE
selectOnTab not only selecting items but also firing the normal tab event

### ISSUE THREAD

**Issue by faulander** [mskocik/svelecte#154]
Hi,
is there a possiblity to select by tab and also firing the tab event, so that the focus is on the next svelecte element? My users mainly use the keyboard and every single keystroke saved, is a blessing.

Example: i have a dropdown with only two items: "F" and "T". When the user types f, the svelecte gets filtered to only "F". I can then select with selectOnTab but i have to press tab twice to jump to the next select.

**Comment by faulander** [comment]
@mskocik : Why is this closed?

**Comment by mskocik** [comment]
Because it has been [added](https://svelte.dev/repl/51f69ecf8db0427da87deaf84f5fdfab?version=3.55.1).

**Comment by faulander** [comment]
aaah, thank you! :)

**Comment by faulander** [comment]
@mskocik : Strangely, i have version 4.0.0.0-alpha-7 installed. Did you merge this only into 3.15.2 or can i use any newer version?

**Comment by mskocik** [comment]
For now it's published only in 3.15.2. Will get to it later today to merge it also to v4

**Comment by faulander** [comment]
thank you!

**Comment by mskocik** [comment]
Okay, I released new v4-alpha, but I think you need to downgrade to 3.15.2. Because I was publishing `v4.alpha.1` - `aplha.7` as latest by mistake. Only alpha8,9 are correctly tagged `@next`. Or you can use `@next` version, but it's missing some of the latest updates from stable version

**Comment by faulander** [comment]
downgraded to 3.15.2 - tabOnNavigate works like a charm, thank you!
