### ISSUE TITLE
Not being able to set custom label for options with remote datasource.

### ISSUE THREAD

**Issue by miklereverie** [mskocik/svelecte#157]
Hello! 
I may be f**king up this somehow, but I can't seem to be able to set the options's labels to a specific property of the objects I'm getting from the remote datasource.

```javascript

       let selectionProcedencia: any;

	function myFetch2(inputQuery: any, fetchCallback: any) {
		return new Promise((resolve, reject) => {
			fetch(
				`https://mytestingdomain.com/procedencia/find?query=descripcion~${inputQuery}&page=0&size=10`,
				{
					method: 'GET',
					headers: {
						'Content-Type': 'application/json',
						Authorization:
							' Bearer eyJhbGciOiJIUzUxM'
					}
				}
			)
				.then((res) => res.json())
				.then((json) => {
					let myData = json.content;
					resolve(myData);
				}); //
		});
	}

								<Svelecte
									{resetOnBlur}
									{fetchResetOnBlur}
									bind:value={selectionProcedencia}
									valueAsObject
									valueField={selectionProcedencia?.idProcedencia}
                                                                        labelField={selectionProcedencia?.descripcion}
									name="afiliadoProcedencia"
									minQuery={minQueryValue}
									placeholder="Comience a escribir el nombre de la obra social..."
									fetch={myFetch2}
									inputId="selectProcedencia"
								/>

```

However, when I try this, it shows the code instead of the description:
![image](https://user-images.githubusercontent.com/42186927/226367105-b0673bff-d15c-4914-806a-76405bdb421f.png)

I'm logging the selection to the console and I see the object with the correct properties, 
![image](https://user-images.githubusercontent.com/42186927/226367557-f244c4af-a36a-4362-9481-657b00f93c4b.png)
so I'm quite sure I'm just making some stupid mistake that is preventing me from setting value and label to the correct object properties, could you help me out please? Thanks in advance for your time!!!

**Comment by mskocik** [comment]
Three things:

- this is not a svelecte issue in the first place
- you should add it into your last issue (#155)
- when you want to solve some issue and you don't fully understand what I tell you, provide a REPL for it - it will be easier and faster for both of us

And solution to your issue is to read _carefully_ my inline comment from this line:

>         resolve(myData) // this should be 👉item array👈 suitable for svelecte

I've added emojis to point you in the right direction. (I am closing this now, because it's duplicate/continuation of your previous question). Open a discussion for questions, not a issue.

**Comment by miklereverie** [comment]
I'm so sorry! I wasn't sure if I should've continued the conversation on the previous issue or not because I wasn't sure if it was strictly related to it, clearly I made the wrong decision. 
I didn't provide a REPL because I couldn't afford to post the private API information I'm fetching from, sorry about that too!

Thanks again for your time and your help, will go and re-read carefully everything you answered in the previous issue.

Sorry, again, for any annoyances I may have caused! Most of it just comes from a lack of experience of my part. Thanks for taking the time to explain though, will keep it in mind and act accordingly in the future!

**Comment by mskocik** [comment]
No hard feelings, I just want to make things clear for the future. So if you still struggle, comment in the previous issue.

REPL doesn't need to expose your live endpoint, you could use http://jsonplaceholder.typicode.com/ for demonstration purpose - svelecte is using it as well in documentation examples.
