### ISSUE TITLE
Make suggestions or completed text editable and copyable

### ISSUE THREAD

**Issue by jbirtel** [mskocik/svelecte#158]
Hi. it's me again 

I was wondering, if it is somehow possible to make the autocompleted value editable even if we do not have `creatable=true` ? Let's say I only want to change the value slightly and only need to change 2 digits or letters, I would have to delete and rewrite the complete text.

Further, is there a way to be able to copy the text from any suggestion in the list or the autocompleted text? I did not find a property to be able to do either of the above (mark and copy the text or edit the text without removing the autocompleted value entirely.

Would be nice, if you could help once more. Thank you in advance

Jonas

**Comment by mskocik** [comment]
None of these things is currently possible and it's by design:
- first one could be added quite easily I guess, but it has limitation only for simple 'labelField' values, ie. wouldn't work with custom renderers.
- event on 'selected items' are disabled. You must look at it as 'item', not just autocompleted text. It's more visible, when you have multiselect, because of different css. It should be possible to add. I can't remember now, why events are disabled on selected items 🤷‍♂️ but there were some reasons for it I would say

**Comment by jbirtel** [comment]
Thanks for your response.
1 - Yes, that would be sufficient. Maybe one can make that functionality only enabled when there is no custom renderer (which means only text ? ) by clicking on the item? If that is not possible for multiselect, than in a first step only for single selection. Pasting text without the creatable flag set would also be nice, then it should simply trigger the search and if there is nothing for that item, we show the text 'Nothing found'. I mean, it should not make a difference for the user if he types or pastes the text, if you know what I mean.
2 - Seems okay. Maybe one can add something like an action button to it. So on clicking on the item, there will be shown two actions (edit and copy to clipboard) with two simple icons. Maybe, it would work to open this kind of 'menu' by clicking on the item? With this menu, I mean something like this, but with just the two icons for edit and copy to clipboard:

![image](https://user-images.githubusercontent.com/57353201/228445427-aaf3a7cb-48b1-4df0-9cd0-5b13bb05b62b.png)
Or, for the apple lovers looking more like this: 
![image](https://user-images.githubusercontent.com/57353201/228445735-196f9822-cf0b-4163-89a0-cc5b9a84c302.png)

For me, it would also be okay to only have a slot and two methods given with that slot (edit and copy) such that one can bind the methods to his own needs and icons or text or whatever.


I am unsure, whether I can do that, as I am not deep enough into your code. Could you try to do this for me @mskocik ? I can also try to help, when I have a starting point or so.

**Comment by mskocik** [comment]
I was thinking about this one... If you create your own Item component, like this https://svelte.dev/repl/f1a0086a7c55423c8d565b175df34d47?version=3.44.1 you can implement custom behavior on click event. Hope this helps.

Btw small mention of this is in the github readme. But not in github-pages documentation site

**Comment by mskocik** [comment]
Otherwise I am not sure about implementing this directly in svelecte for now. Maybe in v4 after initial refactoring, but I have no time estimate for that (aka don't expect this very soon)
