### ISSUE TITLE
Display Fixed Items in a Custom Drop-Down

### ISSUE THREAD

**Issue by saharulit** [mskocik/svelecte#159]
I need to find a way to display certain items in a drop-down menu that will remain **fixed** and **not be affected by any filtering** that the user may apply.

To provide some context, I'm currently working on a custom drop-down.
The last item in the menu serves as an action button, allowing the user to add a new user if they don't already exist. 
However, the problem is that when the user performs a search, this "add user" item gets filtered out, which is not the intended behavior.

Here is the wanted design:
![image](https://user-images.githubusercontent.com/26654228/227770709-72feb626-7da8-470d-9072-939708da83d4.png)

**Comment by mskocik** [comment]
You should use "creatable" property for this.

**Comment by saharulit** [comment]
Thanks!

**Comment by mskocik** [comment]
Yes, see the documentation for available props.

**Comment by mskocik** [comment]
@saharulit Any other questions related to this? Or can it be closed?
