### ISSUE TITLE
Changes to options are not reflected on the selected items

### ISSUE THREAD

**Issue by scoopandrun** [mskocik/svelecte#160]
First, thank you very much for this component, which is very helpful.

I don't know if the issue has already been brought to light (I searched but found nothing), but changes to the options are not reflected on the selected item(s).

Either when option items are modified or when they are deleted, the selected items remain untouched instead of being updated according to the new options.

Maybe this behavior is intentional.

This [REPL](https://svelte.dev/repl/45594401d54a40eb83330e7a902be8d4?version=3.55.1) shows an example with items being modified and/or deleted.

**Comment by mskocik** [comment]
This is intentional behavior - selected items are decoupled from options array for number of reasons. 

In your use case you would need to re-set value. So for your REPL update:

```js
function updateOptions() {
  options = options.map(({id, value}) => ({id: id, value: value.toLowerCase()})) // ⚠️ also notice I am changing `id` value
  value = [1, 3]; // this sets value again to the same selection
}
```
