### ISSUE TITLE
Clicking on an empty input text box fails to open the dropdown

### ISSUE THREAD

**Issue by dinoperovic** [mskocik/svelecte#161]
Hi, version `3.15.x` introduced an issue where the dropdown is being quickly opened and closed when clicked on an empty input box. Clicking outside the input text box opens the dropdown as expected. 

This can be seen on the documentation page:

https://user-images.githubusercontent.com/1486159/228765915-9a8cf404-163b-4c2d-9604-5c4a8c77f949.mp4

**Comment by mskocik** [comment]
I know about it, it was "introduced" in 3.15.3 but had no time to fix it 
yet. Thanks for opening a issue for it
