### ISSUE TITLE
Input value does not get updated

### ISSUE THREAD

**Issue by superrnovae** [mskocik/svelecte#164]
Hello !

When I modify the label of my selected option, the change is only reflected in the dropdown, but not in the input.

Here's how it looks like:

![image](https://user-images.githubusercontent.com/57127875/231584358-c816f80a-4c00-4aab-ab62-7a5cd6f8e960.png)

As you can see the selected value in the dropdown and in the input do not match.

**Comment by mskocik** [comment]
This is intentional, see #160 for more details (and possible fix)
