### ISSUE TITLE
'required=true' Svelecte doesn't show feedback if empty?

### ISSUE THREAD

**Issue by MarkBFamFour** [mskocik/svelecte#166]
I have a form with 3 Svelecte fields in that are 'required' for submitting the form. If I leave one blank the form does not submit, which is expected behaviour, however there is no visual feedback of the field being blank, such as the HTML5 balloon error seen in Firefox ("Please fill in this field" or similar).

Is it possible to easily change the frame to RED or similar to indicate an error with the field?

**Comment by mskocik** [comment]
Hmm, seems like a recently introduced bug. Was working before. Will take a look

**Comment by mskocik** [comment]
@MarkBFamFour issue has been caused by Firefox Container Extension and its' global CSS polution. Therefore it worked correctly in other browsers
