### ISSUE TITLE
type errors in options

### ISSUE THREAD

**Issue by kewp** [mskocik/svelecte#167]
i'm getting type errors when using svelecte with typescript (in sveltekit):

```svelte
<Svelecte 
    renderer='color-blocks'
</Svelecte>
```

```
Type 'string' is not assignable to type 'null | undefined'.ts(2322)
(property) renderer?: null | undefined
```

**Comment by mskocik** [comment]
Can you provide PR with fix?

**Comment by kewp** [comment]
I'm just getting started with typescript. Not sure how you make a library that works with typescript and without. Normally I start by putting `lang='ts'` at the top of my svelte files and then annotate everything like `let renderer: string | null`.

**Comment by kewp** [comment]
Struggling to get a hard link but if you go to `Select.svelte.d.ts` here you'll see how this library does it - should work with both normal JS imports and with typescript https://www.npmjs.com/package/svelte-select?activeTab=code

**Comment by mskocik** [comment]
I know these types can be generated from svelte-kit package command. But 
that's the thing, I would need to refactor the whole codebase to 
svelte-kit project. Which is scheduled for v4 with better docs etc. but 
I have no time for it now.

**Comment by kewp** [comment]
Don't you just need that one file i.e. `Svelecte.d.ts` ?
