### ISSUE TITLE
How to set autocomplete autocorrect autocapitalize spellcheck OFF

### ISSUE THREAD

**Issue by xmlking** [mskocik/svelecte#169]
How do  I set `autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"` ?

```svelte
<Svelecte {...svelecteSettings} on:change="{onSubjectChange}" bind:value="{$fData.displayName}" valueAsObject disabled="{editMode}" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false" fetch="/api/directory/search?subType={$fData.subjectType}">
```

<img width="856" alt="image" src="https://github.com/mskocik/svelecte/assets/627951/a8c440ec-7dea-4ae0-9593-062f686c7561">

**Comment by mskocik** [comment]
Why don't you set it on wrapping <form> element?

**Comment by xmlking** [comment]
> Why don't you set it on wrapping <form> element?
> […](#)

Good idea. I will try it

**Comment by galaczi** [comment]
> Why don't you set it on wrapping <form> element?
> […](#)

Hi, it's not really a solution,because other fields in the form might use autocomplete. 

Autocomplete is the main issue because it completely covers the Svelecte dropdown.

**Comment by mskocik** [comment]
You can always use `autocomplete="on"` on those inputs where desired, even when you have `<form autocomplete="off">`

EDIT: But I will add it in next version.

**Comment by mskocik** [comment]
> EDIT: But I will add it in next version.

@galaczi these properties are already set on inner `<input>`

- autocapitalize="none"
- autocomplete="off"
- autocorrect="off"
- spellcheck="false"

So this issue has been resolved, but I forgot to reference it during the v4 rewrite.

**Comment by galaczi** [comment]
Oh yes, I can see in the rendered page ``autocomplete="off"`` so it's not Svelecte's fault. Turns out Chrome often ignores that setting. I will have to change the names to something more random.

https://adamsilver.io/blog/stopping-chrome-from-ignoring-autocomplete-off/

**Comment by mskocik** [comment]
Hmm, in that case define random `inputId` prop. By default it is based on `name` prop if specified.
