### ISSUE TITLE
Cannot read properties of undefined - reading `$disabled`

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#171]
Getting randomly the following error when `creatable` is enabled

![image](https://github.com/mskocik/svelecte/assets/10332247/2ff732b1-aea1-4c0d-845e-4c7b73f75e89)
the Dropdown.svelte you are using
![image](https://github.com/mskocik/svelecte/assets/10332247/43d02c50-24c0-4dd5-8ed3-98d475c25a0b)

Any tips why this might happen?

**Comment by mskocik** [comment]
It must be related to the your app-specific code. The error is in place, where it expects object, but it is `null` or `undefined`. It means you have option list with invalid options. That's my guess 🤔

**Comment by FluffyDiscord** [comment]
Only shows when built. I did not add the created option to the `options` property so the select tried to access item on non existing index. After manually updating on creating the options prop array, it now works as intended.
