### ISSUE TITLE
Select is cleared by pressing backspace when clearable is set to false

### ISSUE THREAD

**Issue by superrnovae** [mskocik/svelecte#172]
Title

**Comment by mskocik** [comment]
It behavies as stated in the documentation:
<html><body>

<table>
<tr><td>
clearable</td> <td>bool</td> <td>false</td> <td>Display ✖ icon to clear whole selection</td>
</tr>

</body>
</html>

**Comment by mskocik** [comment]
There is no option do disable unselecting. You need to add `required` prop to make it mandatory, which prevents form submission with no value selected.

**Comment by mskocik** [comment]
After some thinking about this, this feature cannot be added without large unnecessary refactoring to keep current search functionality. When in single-select mode, you cannot search, when there is some option selected. Therefore this would effectively disable searching.

I know that search can be disabled by `searchable` prop, but with search disabled and forcing selection, native select or custom (ligher) solution can be used as well
