### ISSUE TITLE
Support for Svelte v4

### ISSUE THREAD

**Issue by pheuter** [mskocik/svelecte#174]
[Svelte v4](https://github.com/sveltejs/svelte/releases/tag/svelte%404.0.0-next.0) is coming, would be nice to be able to continue using Svelecte.

**Comment by mskocik** [comment]
Yes, definitely

**Comment by pheuter** [comment]
Allow me to bug you for an ETA on this, thanks.

**Comment by Buk1m** [comment]
Is the 4.0.0-alpha.10 version compatible with svelte 4? Do you need any help with migrating?

**Comment by mskocik** [comment]
Next week, when I get back home, I can release new v4 alpha with svelte v4 support.

**Comment by mskocik** [comment]
> Is the 4.0.0-alpha.10 version compatible with svelte 4? Do you need any help with migrating?

Not really. I started v4 branch  before svelte v4 announcement. But only v4 will support v4 if that makes sense 😄

**Comment by mskocik** [comment]
Since `v4.0.0-alpha.13` svelecte is compatible with svelte v4

```bash
npm install svelecte@next
```

**Comment by pheuter** [comment]
@mskocik I just tested `v4.0.0-alpha.11` locally and while the peer dependency appears to work now, I'm getting a different error that suggests it not longer supports SSR in SvelteKit:

```
Internal server error: HTMLElement is not defined
      at eval (node_modules/svelecte/dist/lib/custom-element.js:89:31)
      at instantiateModule (file:///node_modules/vite/dist/node/chunks/dep-8609dc5d.js:55851:15) (x3)
```

Specifically, it doesn't appear to server-side render due to `class SvelecteElement extends HTMLElement` and `HTMLElement` not being available on the server.

**Comment by mskocik** [comment]
`alpha13` should fix it
