### ISSUE TITLE
Add scroll event 

### ISSUE THREAD

**Issue by weicheng95** [mskocik/svelecte#177]
I suggest adding a scroll event to the dropdown selection list. This will allow us to implement lazy loading for our fetch response. Currently, we are facing an issue where our query search only returns 10 records per request. To address this, we need to incorporate the scroll event so that when users reach the bottom of the list, it triggers another call to the search API.

In case anyone has to deal with this issue, here's a temporary solution.

```
const ele = document.getElementsByClassName('sv-dropdown-scroll');
		if (!ele || !ele.length) return;

		ele[0].addEventListener('scroll', (e: any) => {
			const { target } = e;
			const { scrollTop, scrollHeight, clientHeight } = target;

			if (scrollTop + clientHeight >= scrollHeight) {
				console.log('end');
			}
		});
```

**Comment by mskocik** [comment]
This is very special use case and I don't feel like this should be supported by the library itself.

I don't understand why having a large option list is a problem. Especially with `virtualList` property it should be fine. Also you can fetch results based on user's search.
