### ISSUE TITLE
provided "value" is invalid using fetch with dynamic value

### ISSUE THREAD

**Issue by webfrank** [mskocik/svelecte#181]
Hi,
  I have a select like this:

```
<Svelecte 
    fetch={`/api/dashboard/measures/${tag}?${q}`} 
    fetchCallback={callback}
    placeholder="Select..."
    clearable
    valueField="value"
    labelField="label"
    bind:value 
/>
```

`tag` and `q` will depend on other fields and when they change the select will re-do the fetch but if at any time the `value` is outside the returned list it gives the warning and value got cleared.

I think the old behavior should be used at least when using a fetch. If not possible to rollback a new option like `allowAnyValue` could be added to override the standard behavior.

**Comment by mskocik** [comment]
I admin it could be re-introduces in v4, but there is one caveat that I won't be able to work around and it is that every dataset _must_ have the same `valueField` and `labelField`.

If you don't want to wait for v4, you can 'unlock' it even now, but you need to add these props: `valueAsObject`, `creatable` and your items must have `$created` property set. Check this [example](https://svelte.dev/repl/8a2e80566c7c410f8bcdc859a52530b8?version=4.1.1)

**Comment by mskocik** [comment]
Fixed in v4, which has just been released
