### ISSUE TITLE
Clicking on the clear icon opens up the list

### ISSUE THREAD

**Issue by szegheo** [mskocik/svelecte#182]
Hi,
when the `clearable` option is set, clicking on the ✖ icon opens up the menu by default. I would like to disable this behaviour and keep the dropdown closed (if it wasn't already opened) but the input focused. I've tried to do it manually using the events and current APIs, but it didn't succeed. 

So I would like to request this feature, which - I think - coluld be implemented with a new option.

Thank you!

**Comment by mskocik** [comment]
You can't disable this behaviour, because it's related to input focus, which always happens, when clearing selection. It's by design. Option for this could be added in v4

**Comment by mskocik** [comment]
Added in v4, which has just been released
