### ISSUE TITLE
Any example for working with dark mode

### ISSUE THREAD

**Issue by ricochenft** [mskocik/svelecte#189]
Hi,
I find it not easy to use this library in dark mode. For example, if my text color is set to white, the input box basically doesn't show have any visible text thanks to the hard-coded background color in

https://github.com/mskocik/svelecte/blob/4f16d7ed2ff07cda1e8426e6895c34d1e4f59201/src/lib/Svelecte.svelte#L735

I can probably work around the problem by providing some `:global` rules under `<style>...</style>` to overwrite the default colors but I just wonder if there are better ways out there to accomplish that.

**Comment by mskocik** [comment]
Styling has _some_ issues... will be updated in v4.

In the meantime yes, you need to use `:global` overrides

**Comment by ricochenft** [comment]
Thanks @mskocik for the quick response. Glad to know that it'll be fixed in a future release. For now I'll use https://github.com/rob-balfre/svelte-select instead since it's much easier to customize.
