### ISSUE TITLE
Broken Mac Detection

### ISSUE THREAD

**Issue by pzcfg** [mskocik/svelecte#191]
There are a number of places where this `isIOS` / `iOS()` function gets used, e.g. to switch between `ctrlKey` and `metaKey` in `onKeyDown()`

https://github.com/mskocik/svelecte/blob/4f16d7ed2ff07cda1e8426e6895c34d1e4f59201/src/lib/Svelecte.svelte#L523-L533

And the comment above it says "Detect Mac device"…

https://github.com/mskocik/svelecte/blob/4f16d7ed2ff07cda1e8426e6895c34d1e4f59201/src/lib/lib/utils.js#L144-L160

…however, by having the `&& "ontouchend" in document` this excludes desktop Mac devices.

I think this is causing some of the Mac behavior to only be triggered on iOS devices, not desktop Mac.

I'm not sure if there's functionality that needs to be conditionally changed for iOS vs macOS vs all Apple devices, but it seems like there may need to be some more specific / granular functions/conditions added to ensure these different cases aren't conflated.

**Comment by mskocik** [comment]
Yes, this should be extended to all Mac as well.
