### ISSUE TITLE
Reset dropdownIndex after value set to null or undefined

### ISSUE THREAD

**Issue by szegheo** [mskocik/svelecte#195]
This is not really a bug, rather than an annoying/unusal behaviour IMHO.
Steps to reproduce on the [Svelecte demo page](https://mskocik.github.io/svelecte/#playground) (Complex playground):

1. Use "Countries" for the Options
2. Scroll down a bit and select a country e.g. Greece
3. Use the "Clear selection" button on the right
4. Click the select again to open the list
5. Previous scroll and selection is remembered (highlighted)

In my current project I would really need to let the dropdown scrolled to the top after clearing the current value.
I would be fine with a new option to let the component work like this, or with a new API method to do this on my own after value has been cleared.
Thank you!

**Comment by mskocik** [comment]
Done in 3.17.2

**Comment by szegheo** [comment]
Thank you! Updated and tested but unfortunately it doesn't seem to work. I made a test [REPL](https://svelte.dev/repl/c49d73c2037e4801a33286573e2a893b?version=4.2.0) to demonstrate it. Also tested it on the demo page. Same result 🙁

**Comment by mskocik** [comment]
I see, I haven't tested this programmatic clear
