### ISSUE TITLE
Show current selection in the list when dropdown is re-opened

### ISSUE THREAD

**Issue by szegheo** [mskocik/svelecte#196]
Another unusual behavior IMHO:

1. Select an item (e.g. Greece on the demo page (Country as Options)
2. Click the select again to let the dropdown list open
3. Start scrolling down the list BUT DO NOT select anything this time!
4. Click outside to let the dropdown closed
5. Click the select again to let the dropdown list open
6. Previous scroll is remembered (instead current selected value)

In step5 I think the list should rather show the current selection (value) highlighted.
Only if not option multiple of course.

This would be very important in my project, because I'm trying to replace my app's old select component to Svelecte with as little difference as possible.

Thank you!

**Comment by mskocik** [comment]
Added. Hopefully I haven't missed any (unknown) edge case. If you like svelecte, you can show your appreciation by some donation.

**Comment by szegheo** [comment]
Unfortunately this doesn't work in my test: [REPL](https://svelte.dev/repl/04002afe0f8b4617a8283ab298cf9bbb?version=4.2.0)
Actually, it went worse, I see some rendering problems:
![image](https://github.com/mskocik/svelecte/assets/37109162/22eff0ee-485a-4874-bf83-7e60523d9557)

**Comment by mskocik** [comment]
It's getting messy 😁 I noticed you are using `virtualList` which won't scroll properly. 

It's weird, that it worked for normal dropdown yesterday... but is "off" now (only the 'active dropdown item' is set correctly).

Will need more work I have no time for right now 🫤
