### ISSUE TITLE
When on mobile the keyboard does not come out immediately

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#197]
I am using Svelecte as a search bar basically. When on mobile, the keyboard does not appear on clicking the bar for the first time - you need to click it second time to get the keyboard out. It's a bit hard to reproduce this example since it affects mobile devices only. Is this a known issue?

This is my Svelecte set up (can provide the functions if needed):
`<Svelecte fetch={promiseFetch} renderer={outputRenderer} virtualList={true} placeholder="..." class="svelecte-control search-svelecte" disableSifter={true} bind:value bind:readSelection={selection} on:change={searchActions} i18n={myI18n} valueAsObject={true} />`

**Comment by mskocik** [comment]
This is intentional behaviour. Maybe it could be added in v4 as an optional or specifically for `fetch` components.

**Comment by maxkozlowski** [comment]
Thanks! Yeah, it would be awesome to add it in v4 if possible - it would be very helpful for my use case.

Not entirely sure how many people are in similar position and would benefit from adding this but I guess there will be a few.

Let me know if I can be of help when deciding how to add it.

**Comment by basaran** [comment]
hi, do you recall the part that blocks the keyboard from displaying on mobile? Is it the input's readonly attribute?

**Comment by mskocik** [comment]
No, keyboard appearance is controlled by `inputmode` attribute.

**Comment by basaran** [comment]
Arigato)
