### ISSUE TITLE
Expose onClick or onOpen event

### ISSUE THREAD

**Issue by Jojoshua** [mskocik/svelecte#203]
I would like an event when the user clicked the select to open it. The goal would be to accomplish something mentioned in https://github.com/mskocik/svelecte/issues/201

**Comment by Jojoshua** [comment]
Bump

**Comment by mskocik** [comment]
This is not planned. If you want to 'listen' to these event you can always add `MutationObserver` to `onMount` method

**Comment by mskocik** [comment]
Because issue #201 has been implemented I consider this one done as well.
