### ISSUE TITLE
Search does not work for nested properties

### ISSUE THREAD

**Issue by peakercope** [mskocik/svelecte#206]
To reproduce:
1. Open https://stackblitz.com/edit/vitejs-vite-avofes?file=src%2FApp.svelte&terminal=dev
or use next template:
```svelte
<script>
  import Svelecte from 'svelecte/src/Svelecte.svelte'

  let value = ''

  const options = [
    {
      value: 1,
      label: 'Label',
      name: { value: "Chrome" }
    },
    {
      value: 2,
      label: "Second",
      name: { value: "Firefox" }
    }
  ]
</script>

  <Svelecte
    inputId="test"
    searchable
    {options}
    bind:value 
    searchField={['value', 'label', 'name.value']}
  />
```
2. Try to type any value from `name.value` property (e.g. "chrome") into autocomplete

Actual result:
"No matching options" message appeared

Expected result:
The appropriate option must be found

**Comment by mskocik** [comment]
Nesting is disabled for better performance and there is no setting enabling it.
