### ISSUE TITLE
[Feature Request] Allow duplicate selection for `multiple`

### ISSUE THREAD

**Issue by fkrauthan** [mskocik/svelecte#207]
I have a use-case where I plan to use `svelecte` for a check point selector (selecting multiple locations). However the user should be able to select the same node multiple times (e.g. City A -> City B -> City A -> City C). Is there any way to allow that with svelecte?

**Comment by mskocik** [comment]
Svelecte is designed to be used as multiselect, so this use-case is impossible. You cannot select the same item in multiselect multiple times. Selected items are tracked by "value" property, which means you can't have the same value selected multiple time.

This can't be implemented without huge code changes that are simply not worth the it.
