### ISSUE TITLE
Options don't appear when typing (mobile / firefox)

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#208]
When you try to type in something on mobile/firefox, options won't appear. This effectively means that you can only select from the list but search is unusable.
The issue is present for example on the svelecte website: https://mskocik.github.io/svelecte/

I have checked whether this issue is present on chrome - it isn't. On chrome it works as expected.

See an example below:
![svelecte](https://github.com/mskocik/svelecte/assets/42048060/7c0a6303-5158-4c7a-b9a4-ece97db86a6c)

**Comment by mskocik** [comment]
I can't reproduce it, works for me on FF
![Screenshot_20231105_145517_org.mozilla.firefox_beta.jpg](https://github.com/mskocik/svelecte/assets/25513620/b8a5ce46-931d-4c3f-be99-a0ebf2da9097)

**Comment by mskocik** [comment]
There is definitely room for improvement on mobile as we discussed previously in #197.

Note for myself: There are weird issues with `backspace` eating presses.

**Comment by maxkozlowski** [comment]
Thanks for checking! Sorry you couldn't reproduce the issue.
Is there any way I can help with understanding this? If that helps I can try some other mobile devices too and see if the issue persists.

**Comment by mskocik** [comment]
No need, I have access to browserstack - so I can test it myself. Btw what mobile Firefox are you using? I am using Firefox Beta app.

**Comment by maxkozlowski** [comment]
Thanks! I've checked on both Firefox and Firefox Beta (and the issue persists across both).
