### ISSUE TITLE
Wrong message for empty results on remote datastore

### ISSUE THREAD

**Issue by evgeny-sureev** [mskocik/svelecte#210]
If remote datastore return empty results, we must display `i18n.fetchEmpty` instead of `i18n.fetchBefore`.
I think there is a bug on line 220 of Svelecte.svelte, `listMessage` created as local variable instead of setting value of existing global var.

**Comment by mskocik** [comment]
You are right - `i18n.fetchEmpty` should be shown, BUT I am getting `i18n.nomatch`, not `i18n.fetchBefore` 🤔 

![image](https://github.com/mskocik/svelecte/assets/25513620/16af4d91-db17-4bf3-a035-3a1035f6723b)

What is your setup, that you get `i18n.fetchBefore` ?

**Comment by evgeny-sureev** [comment]
<img width="668" alt="image" src="https://github.com/mskocik/svelecte/assets/7701455/3820c4ab-44dc-499c-9b01-f3275e71f24e">


Here it is on Svelecte demo page https://mskocik.github.io/svelecte/, displayed text 'Type to start searching' is i18n.fetchBefore value.
