### ISSUE TITLE
Would it be possible to select some option and change or add some string to it?

### ISSUE THREAD

**Issue by usmakas** [mskocik/svelecte#211]
Would it be possible to select some option and change or add some string to it?
Example:
I select this: Personal statement example for **graduate** school
And then change some value Personal statement example for **high** school

The current situation requires me to remove my selected value and type my value from the beginning.

<Svelecte
                required="required"
                labelAsValue="true"
                keepCreated="false"
                options={[
                  ...new Set(
                    handleOption([
                      "Personal statement example for graduate school",
                      "Technical writer personal statement",
                      "Design assistant personal statement",
                      "Data scientist personal statement"
                    ])
                  ),
                ]}
                bind:value={object.type}
                highlightFirstItem={false}
                creatable
                creatablePrefix=""
                delimiter="null"
                allowEditing={true}
              />

**Comment by mskocik** [comment]
This is not possible, to change "text" is possible only for newly created items when `allowedEditing` is set to true, as in your example.
