### ISSUE TITLE
How to concatenating string on label ?

### ISSUE THREAD

**Issue by kodaicoder** [mskocik/svelecte#213]
How to concatenating string on label ?
or I need to build Svelecte as custom element to handle this situation ?

**Comment by mskocik** [comment]
I don't quite understand what you mean by that. Can you describe it in more detail what are you trying to achieve?

**Comment by kodaicoder** [comment]
Sorry for that,
I mean
If I have list of option data like
```
const options = [
    {
        id: 1,
        firstName: "John"
        lastName: "Doe"
        Department: "Test1"
    },
    {
        id: 2,
        firstName: "Jane"
        lastName: "Doe"
        Department: "Test2"
    }

]
```

and I want selected options and dropdown list show a label like
"John Doe / Test1" , that mean it need a data from 3 field and concatenating into 1 string and with extra slash
then how can I achieve that result ?

**Comment by mskocik** [comment]
You want to define [custom renderer ](https://mskocik.github.io/svelecte/#item-rendering). In your case something like [this](https://svelte.dev/repl/17c175d1012c409eba720e10c2413024?version=3.44.1)

Check the docs for more advanced customization of item rendering.

**Comment by kodaicoder** [comment]
Thank you for fast reply , I think that a solution for me 🙏
