### ISSUE TITLE
Unable to drag items when using {dndzone} with collapseSelection ={true}

### ISSUE THREAD

**Issue by macsupport** [mskocik/svelecte#215]
I am unable to drag items if I set collapseSelection ={true}. When attempting to drag, the dropdown collapses and the selections disappear. My set up is simple:

`<Svelecte
bind:this={svelecte}
inputId="drugs"
{dndzone}
name="drugSelect"
multiple
bind:value={selectedItems}
	valueField="name"
	labelField="name"
  valueAsObject
	placeholder="Select Drugs to Add" 
	clearable
  enterKey={true}
  closeAfterSelect = {true}
collapseSelection ={true}
	fetchResetOnBlur={true}
	resetOnBlur={true}
{options}
on:change={handlekg}></Svelecte>`

[Here is a fork of your dndzone REPL](https://svelte.dev/repl/ccfc6fa163194a29b24fe2119f18df2a?version=4.2.9) showing the issue

**Comment by mskocik** [comment]
Definitely unexpected, will take a look what can be done about this
