### ISSUE TITLE
Feature request - hide dropdown arrow / entire item list

### ISSUE THREAD

**Issue by foochris** [mskocik/svelecte#222]
Thank you @mskocik for your excellent work.

Is it possible to hide the display the list of all the terms (and the dropdown arrow) upon click and only show matches to a search query upon entering the text? 

I didn't see any option in list of properties to accomplish this.

I have a requirement that upon focus or click of the component, the display of all items is not allowed. Matching items can only be displayed upon entering of a search query.

**Comment by mskocik** [comment]
This setting is not supported and I don't plan to implement. But you can work around it by hooking listener to inner `<input>` element and apply CSS conditionally. Something like in [this REPL](https://svelte.dev/repl/cb58a68430a24536854eaab5bcf6d771?version=4.2.12).

**Comment by foochris** [comment]
Thanks for your REPL suggestion as I was able to fufill the requirements. 💯
