### ISSUE TITLE
styling open select

### ISSUE THREAD

**Issue by nosovk** [mskocik/svelecte#223]
We can pass a slot, that will be rendered as an item in a selected state, but I can't find how to pass a slot to style opened element. Is there some named slot or any other way to style elements in opened list?

**Comment by mskocik** [comment]
What do you mean by "opened element"? Is it option in dropdown? If yes, you can use `<slot name="option>`

What is missing from your point of view in [docs](https://svelecte.vercel.app/rendering#slots)?

**Comment by nosovk** [comment]
My fault. It's there.
In common, the best is to put some example into renderer serction.
<img width="643" alt="image" src="https://github.com/mskocik/svelecte/assets/1398808/563c3e76-f7e3-42c3-82f8-8bcc33016651">
Like this, to show that list items could be customized.

**Comment by mskocik** [comment]
You mean like in the list on the right? 
![image](https://github.com/mskocik/svelecte/assets/25513620/e6d62261-ccd4-4846-80e1-2c3969350471)

**Comment by nosovk** [comment]
Yes, but from the screen above with red rectangles there is no clear what exactly is possible. Actually I got response from team-mate that it's not possible to render custom slot inside open slider, and after that opened ticked. (My fault that I didn't check it carefully). I think that my team mate browsed examples page, didn't find any one with custom slot, and probably go to conclusion that it's not possible (I will ask him to confirm that on monday. It would be nice just to extend example with colours, with additional block showing how it looks)

**Comment by mskocik** [comment]
So basically you mean something like [this REPL](https://svelte.dev/repl/60fc13a97a7c4d7dbb7ae9080d558ecb?version=4.2.15) should be in examples.

Documentation could be extended for sure. Slot usage may not be obvious. Unfortunately it's quite time-consuming process, which I don't enjoy that much and it's hard to judge what is not clear enough (author blindness).
