### ISSUE TITLE
Setting CSS

### ISSUE THREAD

**Issue by macsupport** [mskocik/svelecte#226]
I really like your project and it works well in my App, but I am having an extremely difficult time with the CSS. It seems impossible to set css to fit in with my UI layout. I understand it is set in  Svelecte.svelte but changing it to fit in with my App CSS  UI (tailwind.css) has been very frustrating. No matter how I try to alter the Select CSS, it has no effect.  (Using global: )
Text is too small and is truncated, the text input width is about 1em, etc. Some help in this area would be greatly appreciated. or an example of how one can reasonably alter the CSS.
This is how it looks currently

![Screenshot 2024-04-29 at 9 24 17 PM](https://github.com/mskocik/svelecte/assets/624656/e0b23b0e-671c-4db0-94dc-094429588aea)

**Comment by mskocik** [comment]
Not sure what your styles look like, but try this example of [custom svelecte styling in tailwind](https://www.sveltelab.dev/?t=tailwind&files=.%2Ftailwind.config.cjs%2C.%2Fsrc%2Fapp.css#code=N4IgdA5glgLlEDsD2AnApiAXKAZlANhtiAMZIIxoUDOWoA1lAgCZYjUBua%2Bl%2BAhgCMAtAFcoADj4gANCAEicONCiwBtACwA2aZvHTxAZmkBOAKz6jARkvbrl6dfUOADPcvOH7z2%2Bcf39sxdjbxc-SwB2Fz1-T3MvdUjjaIiXOOdo3xdpBOzbSzjLDJ9k21dstMj3AtLsyssAJhNE4PdEyucrMvjSty9rDNyXXrC9LWzGrwMjMZjrEcHrc2N2loaooaz%2B1M8eweNV4ZcJ5zTp0rzzGZtt9xau-J2moM9G9UvjzwzqjbH9kLmjjcOgtrosQaU0ndet9ls9rK93i4ALoAXzRsjAAAd0DA4MoUCQ6CA8IQiWQKFQYLRiIwWGxONxeIJRBIpLJ5IplGoGp0TNIDE5rHU0vZxE5YUlYvynKY9AYJqDLIKUjF1IKPMEBVKqp4-MD3EV9L06r1dlrZfyFXlle17GqsprldanjqDTc%2BsDNCa4c5grDzXLGlqAXZdRstfavI6Xp51QUwtpxO00gmXE4A5bssF1KNRuq%2BcG1m6hS5OvGpRn5SZ7IWFerTY9XfcnG8Y8WVfqTmHW2CtrN0o2ylrjNN89H4esS%2B4y2HDBtYY4THcnLp3crzJXGsYay3tMPRw7pf9ChtF2eu%2B49dCjxaq9uHPUjFXg85jmlDWDN0f1K8Lp9TwO1hmi26ZBsqvRWu6hyfjKgYPk%2BYExguSras2N5wYWBQfoBoJDqBD4bhM9RLLyDRpKi6IgJifAkPQfAQGgYAAFbUOQRIkkQoDkpQNBErSrCYOwXA8NwzJiJIMhyAoSgqJgqg8oehYais4awZmmH-v2JQAXoEqjDCyaTpYdzlpe35jkefZob2F7WGGX4RqM2g5oM6jRpGGqWUWKGuieyHAdIt6QWeHZ2hZha2PUEGqYFGHqgcoSeO0hoRuF65LrG7rBQ8X4KVGBbiskhnFpkDnKl8g41luRVAhkHipYe46ZLMJ5lZptlmscV7-g1%2BXjt59btSKnjRkFXkVUB4YKnWp4nk2vTuRZTUKr08UutcbUTueDaTfNmVVq2PZFjh7QzgCR3Dch4rLuUiW%2BfhYwHZcBSrHGlWZo9IGNUefzuINv3OJEm0PFZxTvT2gPunuCpxFFYZ-M%2Bcpwb2c1dDhuytgD-13EDCK3btDy-XZIavkCCGue0f5E9BpNNmcLh-qGAIvnyZHZGld33Hoq4tccNPdQCAPDTBsWZnlnnRpo6Wg0ZuzuH%2BOQLpkyHBWhmN1HUeQ7qLz7ijKdrOU52Ryl9fVHlL2qo2Du1owr7TFRtam6yYMoeGMLnuyb7PfVqFso9h2n9nbQ3gwUxw1dO7puwUWE6e9bXGPrrlGy5vUSz9GuNsTA0AW%2BD4CyhCcttmRumL%2BgUbqb6e1seMKrDH6HqXrgXOdoZeucE7dp3y-UrZb2hEw3EPJAE7TRxlTMennkdF4F5ce85i0%2B8qM0tXkEKzemTuIYngVu23rfG%2BZy9tj59zr0Cq348dEeduWF3tdbuHa2Nw6ux3R-u0vZsaTL7YBa-Zu7dPbJ2Pj-aWVtZY-CWDdGIAMgbbx%2BknMYwC27aw8j3LysctKh1PoNLaPk7IA2vCLQBLtAr0wXnPMB1cnQugvDhEyYYzKDwrIgt%2BgUDZZkGKYJ8VdMGFgms-Ruztd68NASAlmLRiLe3yi%2BAufNmHNXuBqJhLVK46yIryP0WDH6TjKETABcVyGoO4ZIiybM%2BgyPcBRFEshMRIGoDAEg1BqBgHJHgCA7iWLsQIJxUg5AeJUj4kwASQlGSiWEOJNkUlOSyVUNTZhIMNqQSVu%2BEaUdEqsM-I0TQVVMotSsB2Aog11D1VWAPYqjDMksPrhWbM9hTB3AntnMI3w7yZwJtFbagJXT1ALvhPJYsz69CKQ7Up5T1qa2PKvNG09%2Bmb35A0wKzSowJRDMk6GLSabT2BFWIZVZxasxvklUsNSHhjXvGbHIOQ5xM19FNNsJ0zm%2BTad7Q5gEGG2mGZU2qGTXlZLqWCHIJMSG4VMsCe0hyPQ%2BB8PVbK%2BSQp1HhSYbCfcelVjFPQ9J1g1EejdktR4aSjJ4r1Koy2lw3ZhW%2BjcyImg8jTOhTtZw%2BDCGXHwiVCojzkLTMnrMnw8yBnvIVALNGKKunDJtPZLc7RVZXwwTonlWdukjN6ReBZLUlqkRkU0zYep1nNQ7IaGYXQNXeSvgTQiOh8mJJJrsowuqbFojsewAkRJmBQHQCQGAqAACeRI%2BCYkxO41xvjSTEG4pSakDBQn0mEkyKJrJJIchkmoP21xiXtlJYlO8ulhQbEdR4dNvymzJGzWZO8BrVjophUkv8hadB0MzdUgFFaFS8oYUIje6iVl6tFiFXoDZDmPkPIdBurRbqSglDjfGLLNF7yPqYGUzTszPVQpETGeaJ6Q1bKYO0aRpYDjGg21d18uWbqePA26bl51-VQqMN2eYPpyg3Q9EuR8DAbsaSu6946d1LC3Ve3dHgxp3psg%2Bz%2BD0X3CrMbmfkX7e35THeuydgGZ27sacjOd4HsggcfYFL6VYl3UM-TB0wkRTB7gQye39KGL3TpcBu8w7dQPYZBgOMpC6XLEahY0FjQZX2ZnI5w%2BD2Rv2jrXTZJjqLL3oeYw6rDh6IOmHwzx-CKmP2CaI4bUT6hxNIck%2Bx6TNs3BmucpcTuin724cg8%2B3Tb6ROkb04hzyyGpPXzlmZ26GnWNKZsx7KD9mhMgY3NRn9bmjMedPF5jDt62PpM4z514T7tNBaI3xgTYmXN8gi%2Be74YG0ZQmvZZsW8X1icZveI3jsHNNkYdU%2BMLEmz2MaiwVnwRXgNxb84lkDyWyNUbIxl3T%2BnXOGby4OfBDzVTMcw6V7reHF2vAcx7aD1XiN7uG9l09D8J0QxramV%2BwRwirA-IQmVFKlkwfVqfcO0DtRwxRnLB51X6X6IhZEcIbQMp3Ie5sgCR2wjQWuNVgwwQ7loyKbCzM4hzDhCfNmfC4g%2B6SknlrGDx384Ph8J0Q41WYcyanH0RUgmzZenWqmK6cc3Qg4B2uJ4mKjDITeaDmDLOeaEJ8CmaHjPkX1NZ0dxR7ZTsbz%2BP6Ro4RTvfJZ9VsETOpQ7esgwvj4Wxstb28eVMEN1lE9m8%2BWn916fi%2B9BsmsCPSva8B5bc7xDsuWL1AT4mzU4bDu0TJhjE7I4DtOSTcetqcJX1A35OoLZx4K%2Bk1O5oauZtZZo37kemVA9bsXBV1Xu38ums1xZmPP7bjrXVGdLwY0qGmHk-9rbvTWmPHV0rNRgE4aJ7z-51P-6K9A%2BciNnukebcbPM9soyAfkZB8yin5raeJtl%2Bm2Yjvdush%2Bym2K7YYubMEMm4Ltlk6DXx%2BTw3LGE%2ByiseUgUndiKR35QtF71HYtT-p1y1Ht3kex%2BVaszhirKW%2BtOeW6tjvOjb9j4j9u6THzZ-djCDALOzD-D6TuAbZzWPWjdzejB-FvDbXzazV-K7VbBzLuRra5ZvcPNDO-FjYAhLfDarVOLTPjBbJzb-HLXA1DWTAghTObVAkgwLCA9LWrGAn9bbP9YzYRBoTPbhFAl-Fg8A8gwKDdL-cvbgujdPUzAQoApg4Q2zA6DAoTHTKgqQuAyLI6TzeQ3XY4ebZQ9-MQ9bBrbPQ8GfPqLfJ3E-V3P0TfY8FsHfWBQrAtLDQ-c8CjHPaxe3P0XGeCb6OPRw29IfZPUPHg1rbDVwyfDbTgiwnwxqCjZIIRNIWQnNLRQIhwyeRBMDEAmzHzGUdlSAz%2BVQojUvDQmjSwhIrwOfJPB7NCStf4Kbc1JRNvCsDIpDRmSBEqAICpR5I5TUIMPGHbE8LXTJCGSbU4NMR4Y9PrLaBZGjZ8YY8dUYgDM5V%2BaPHzRpJOdwZXRSIYrQ2OCGPUHfRIDIbCX3DIRg58YWNGagpYw4-8C9bIzmAfYo%2BY8VZJa2BhFFAwZjd%2BdbEDAEn9B43-VYh3C1ZReVEpehE473C5OCduD48vUE1PcEz3FRRZJWfSJCMeTmCFa4obZExYg4sEnE21InZ0e5ckq4kIpPFCEfEYmks5OIuRUktEnE3yJ7U9XFTKFWa%2Bc7MyIU2yPUQkkTZEojbpBZSUtsaUvjFeTHEkj6Dk2dNI3PBXb43o96MyZ44EDYgjBdQEg0nzEE9k0fdEjqMvZ4xUX3LI7OdhGBDKP4JUp6c0zky0-sU9FHG0jfJorfBkg9Y8U7B0p0%2BwlEs0pk1U7U57NYgmS49YjCf4w0gE4E-Y5Ut0qMkzZ4a0vIeMyOCYoMxZfUqdTuFsPQdbe4iMlY90x0yeW0v04I4s3SZs8M9MyMiGWsyvTGO06E6YyeYM%2BdP40MjKF05Yy2Gsvvc6WMvUwfZ0OXFGQU1VHvVs109s1Iyc%2BIP9WGRRY9fDYk00ts6s0fe4Rc8UXle0ugyOfUo0m81Mtkw88cy8n060yEoVIvcsg81co8o6W7d3NGcCfRIVbshsl44ssM0XO4IElcsc-2WdMIACraQ1BabsacsUrYSnRk781C8w%2B8r8x844gpbOLqY8VYPMi84Ut46FekkPR4rYF8o-ICysh82Cgii-Y6S3Xkqcpo44GGWaNuOCG9fctMvClirnNi4iyeUi6%2BWvVMO9S5TpRUJikS5Jd0%2BCmZO6bOKShXM8jS5C9894osOU8Uwy340vcRcyz8mClSuCwi7pJC-5TcvstGKY3I-ioTRpPcky6C2ii0tSvlXShy33B-cFPRXUsUoc8yh1OFcUzIUcny1S2yp5Di4yFC1CTUlpJ7PMmc9SZjMyvjB1fK7ysk30npfyO7CdFHTIei88N8gS6tTHaFAob4rnG440qCgow0yy%2BKkq1VMqyfCquqS87K1q285Mzq4Sqyo4zs-6DtfdfEqUPSfRaKsKwctILcP0QDLdOK4q4eEIJWIC2M8iqEhPREsIIiT4pqt7dI-kJMjqu6kDbwpYTYYiWxWQQNYNAACxgAAFt8Aw1-FI1eIaRY1BIGQRJ%2BBE0JJ2RpIuQ5JNB6ojBVwMcycsVxAwci1Bi%2BzcI7huYPh4asbSgcbSt6TRTrVLJMTfYPgai9QZrEpNAPhgh8bc815Ddt0dKQphZrgDkpUbY8ZKMjwDo6UGadB9U%2BLWbBYVIYhuaQ4Wp6qXjJotRGi6ztTKSybCwZLx8hkKKQ4bcjoNabYt4PohbDwmbPl3tJU45padQKT6oOU2NV81b0x80-50YAIHZD5kI-0docoN1ZV1oKobaQQRUzlFbXhja5FnbujXb%2Bx3aFgojR4c12gRbagnKE6zJ6a%2B18bvToqGhEVlZplYRIycEsyPdLSfyj8n406qqucyrYQra2NegBzKaTayV3RB98t6jDR664SFz1gFx684JA6S7VaRYM7SNYLi6%2BDIYuS9hrC-Bnc6U3Y8TfJcbZ8l6IS7o4YM6PRk6QU2NCb1h6bXqQB8AoABB3VPU0BvU-UiQABhJAEQCkFAMAMGygf6skQJKNEJOkUG%2BNSJFkKG2JVNOGt5ImN6AhbQbezyHox4JW7OXnBW3JfJbjVZTyAwNyj5Naj6clSeBBlJHQJB4oj2WwwI5KRZSaTjYwAebXPBrZXyK1FhBBzsC1eB6zXOxQhhTodMRndvTQik2hzMA5PjLw%2BItICw2mFUNZQcS65mAw8nTmLush629DKlK-OwjcgRg6RG5BzuR6telO2XV6LKR4KB-R7088tHWRjXUWAGAOmdLW6-dm-FJanQJRrsK9NmJWgcT2qUaW703MzMfx1Kyq2%2BbWUxxmtx2s6ehfF3DRutAieIxnGh%2BJ-ZewIZIR7hfZcmFnG2SEcMTGw7aRn0a8HJhI-GxWCORUSxmoqmotN5XaTu-o7xph7RryGtOuC7Zuzoh3AJ2J0nJx6aScZ3Hi6xihw674z4oiOajTaFc67zA4tiph0VB60R0dAeQORykJ73IcDo9OC2fkxC6IYZgnSFac0J7zaYODaFXQqvF6JytIyohI7MdZrOLK858-BuvRRcPpvZgZp5I5m1Wk3U853dS4ODR5sR8pyOyKdKqB2xSiFAB%2BygaNEAD1L1H1FAf1YgAAan4F9SRZfr-vfojU-qBpjR-vCXBrEiTWhriTTVAaMd8kgnCaBDlvIvwel0PkVjqEGd%2BCBRyl0f0ZBUJkZdsmZdqeTpw0v0FoIeRGdVkGxeogYhfuUC4Gfp8WIA4g-opDJZAH4jjQiQhoAZiRTVhvkgz1PhYa2SHr%2Bw%2BXj32sEZtWdt%2B3JQOlUdSdlZ%2BeOVZQZUIvFWv0wQluKcHLB3Zs7X%2BRFJzT0YbTZkLWPsVfokYlfv8S1ZJZ1eCWBopeTaNeiWTRhviSZpFaPzDhMeFqbDZatcEeN0kdkoaJGYvweT135FKADtGDpWrYEc1RBGwTRkDiHEFfynLctcIq2TuSjsNEMSadXkd0xpyesuLoMT6JiBZ0qItYIUrbtbFo%2BQ8IzREZ3qJpZqZVPm7UrxyTVq3FN2kAx1BUzHqE43yBaD9hyGl3whZyxU4rsirDvb8EdSRIMDlDNybffftoAnyW-YcEdT9k0E1D9F5ChYWtFZLcmlMepumJvS8fpIbitr4Ji2j34PWA%2BX21uY3pKk%2BJubGerBurVT4yhxWxMD4VlfynCEF0%2BXjx%2BZ3d%2BSuA8Pn1Mw3Dg-XrvRvRQ7qdcePE7brZTtMdNuVHwlsfWiw%2B1mZrhl3UQik48DHYDnnCXZ2YCP8tydGZBhkRlbhedVM9kCcT4DgEJGIDRavoxaxdwD4A4CgHJCxAQAgGJa4lJYzfJbCWzepcAdNfiUfBaCuTRv0A8AlyvbcF5HqBqA8AS4cCMDhyvdyT0CR2kES-3ky5y9tuyH5Fy5y5C4cDC7B3MGK%2BMjcHC4aEiCy-5CMHEEi8TBXGCDq4q9K8bSK5yY64tg8Ha6q8ZqcD6%2B64G86%2BG9C9G80HMHG5K8m6G%2BkH64cHC6m664m6W8Zum4W5G-W7G627W8KEG5y61CxUW4O4cFq8K%2BzkTHF3S6MBm8q529O-C6e8O5yBe8QxPHe6%2B-FwW4%2B3sDq-quY-0DqUS5Qne9B6cHe-sHe-UCsEh4u8S-e5S9XBW-fYWS%2B%2B27O4x-2%2Bq8iBh6Ob29m52-vCocJ4e6x8x%2Be8p9a7J467WGx6J4p5x87mh%2Bh%2Bp9p9G8sCMAZ-J%2Bq%2B570He-bhS6mAKXqCDGkXK-Z55466R%2BCGl9G7vZMCIlKG56l7Z%2BZ6W8Cg58e-Z6sEaHqHS8N88CKX16a%2B17O95Kh7F-N-C7x-Z4Unl524zsF-FEaHu5l9ytW8Z-C-EDSfd4V6l8D419h%2ByAdTt41%2BBVS4oRt7l-V%2B97l6l8qHR-t8l416t8h-t4ZNV7T6D-j4cAz414xxD4MAWwx0a8xwUk%2Bxj%2Br6h4HEd6Z7z6igmGvYo2Y3FzcAW4vAMDj954T4j%2BSQL8b-t67He%2Bg4rmr%2BMkFCr8XC%2B65-z%2Bz6H4j-qNabBF1St%2BmFT8X63975CCh7snr-C8lBL2vkiDR-U83537363H19z539zyt5746%2Bc1XBkQP%2BkUf9G7GDf4XRZyikqFI2-5zgYekeIztoCB7vcsUQ5MELXzwYMdNAC-HfiH2-7ICoBPYR1PvxSr5BuY48b-vAOr51dIuiNI7NzAF7s9XspPF7vCxdTJt3E5ATxMxBRapsvO6bFFvq1-qGsAuJrfNtyAYQVsR2wyflHgj2pFYUYDDCRghUbbi9Hyk9DGEhyXI5xQw3eZJBuAHY91miNaOhB0iyQ8sVadtadu1nUiHcJ6vbaMsHAdYHM%2BCAZKZMqkuwxt16P4cYIIzoTsNEKJDIduu34GcY2cECTTiXWcDBxS67SZZGMDJzK1diZMBJgdDDoOgLc-cQJrEPCF0xHWajcRrHVAwBsf8vtQJniQsFywrBSqCVEexJgAthkBQHQR4JCh-hGqTRIrB8iBxCIEKHoEQSPQeAy52MUOD5M4MVC8ULQtKFrDPSuA9sn4GMUoAXDbYBVWE3LbQce0WTXZCcaOQjsES0Gbt6GVeGoJkJTpVgUu4Q4dIOnhJ216hdOMITxxSbTwcowdaVrxUJyDN5aU9T4lfF2FidShYtG2BcWGSHBlhVw46FqSbB5wEYa%2BeYAbmOHNDNcHKZJHimobTEihkjOhrhEGhaDGGMwrtiakwR9CGcoHRQlU1PjMZxhe9WOoMK%2BbR0ygJqMYQY3sqTCvsiIiBuQ3OGt59oxwbXPCLOF6gNBzwPqrZA%2BHW5-SjKQUvnSRHWRWh6wzvNMOpFdt5KIo7yHkJorOZB2MiDBIOwUEnlEqSghuJch8CBtFRKqACiqPlzz11GfAx7C0lVGzlCK3yM2GzBlESxtUzGVBtFjOrBFEGrxQEAUNdpwMdkEQuNvKxAAwA%2BABAAAO6hJaBCAegSQA1a4A-E2rIJKwJBqUsE0xrPNnSzkg2t2k61UZrTE4bJCvWYZMIZYIOyD1L27sSOtdBToODSxG6cuOLGcHz4n08seXD4KpzCJIwioWGCoPo6yJfC4%2BT0m4RSHmi12uYxKOkL15iMJe7YiwicinB3wkkOIwJgEGtG25Ra9yMIG4y4SzAzUrIy1JmNTHHD7ULmY%2Bs50oBBj6BYY4kBGLTZRjv6fnP%2BjmxpZAMzW7glopUJSHVCXafbHwLHWHRiD9BzwJtumiGFQIg48ue2FDAMaow0iK7VBnkwqGEI6GI6bdrnBqRlBQhp7dMVMQ-GlYvxueJtlZDAmqC9UchYdo%2BLgn9hFySjfBtrUSGRspa1bFkREPvYZD-m2zAvG8jVHSCTBfg-EaoxHDPVLgI2eFkAA). Check the `app.css` file from line 57, where I added "default" properties for svelecte. You could also redefine style for inner css classes which svelecte uses.

But in general I would say, default 'layout' css should be good for every or at least almost every use case.

If you find something not working, please provide example with issue.

**Comment by macsupport** [comment]
I really appreciate your example. It helped quite a bit but still having troubles with other CSS overriding Svelecte but working on it.

**Comment by mskocik** [comment]
Sure, let me know it you encounter something that is impossible to customize or some additional CSS property should/could be exposed. 
And with some test scenario (similar to what I posted) so I would be able to take a look.
