### ISSUE TITLE
Svelecte: Unexpected mutation on a specific scenario

### ISSUE THREAD

**Issue by jamesst20** [mskocik/svelecte#230]
Hi,

version next.6 did fix many mutation warnings I had, however there is still one instance that I have the warning and it's when

```
<Svelecte
   ...
   value={...}
   valueAsObject={true}
   strictMode={false}
   onChange={...}
```

It happens on page load and on value change with these exact parameters. Note: bind is not used on value

I believe the source is here: https://github.com/mskocik/svelecte/blob/master/src/lib/Svelecte.svelte#L473 but I didn't check for sure

**Comment by jamesst20** [comment]
I've got another case scenario

```
  let testVal = $state([]);
  let testOptions = [
    { text: "Test 1", value: "test-1" },
  ]


  <Svelecte
    bind:value={testVal}
    options={testOptions}
    multiple={true}
  />
```

It happens when I select an item

**Comment by mskocik** [comment]
I am afraid this can't be solved right now. I suspect this can be some kind of svelte v4-v5 interoperability bug 🤔

The bad news is that for fix whole lib needs to be rewritten, good news (for now) is, that it's just a warning and doesn't break anything.

**Comment by mskocik** [comment]
Because in principle this [REPL ](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACn2RwWrkMAyGX0WYhczA0LAt9JBxAsvel0Khl3oPnlhpTR3Z2MowJc27L3bKzNDCGnyQLP36_WkWg3WYRPM8C9Ijikb8CkHsBL-HHKQjOkaxE8lPsc8ZmfpoA3eKFNsx-Mjw248BhuhHqG7qHNysbdU-F-XrkOGo3YTQwo_EmnFT6UNvsNruFcn6okkPOiIxlKJmLk2LIvkaO0WyTCq59vMJ6tIlDxOzJ_DUO9u_tfNmC213nlnpcqqlezw7YQ-y9wa79U3WJZD1qtQpEjsxemMHi0Y0HCdcdmdI2cj_KZVU4wNbTwniRJjaedAuXTxfkcRTIXnNiSbnMkBSPEzUZx1IyIxxs4W5kOXz_37e3q20ly84pbFHSPzusFXi4KPB2MBtOIHR6RUNRDR7CNoYSy8N3IeTEp2i_D1PeQ9PeUID86etjw9Q4o9neERWYpGHspav8FebK-yLVFG44itrY4_dd8p_l38x8H18lgIAAA==)works the same way... So I don't really understand.

**Comment by jamesst20** [comment]
> Because in principle this [REPL ](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACn2RwWrkMAyGX0WYhczA0LAt9JBxAsvel0Khl3oPnlhpTR3Z2MowJc27L3bKzNDCGnyQLP36_WkWg3WYRPM8C9Ijikb8CkHsBL-HHKQjOkaxE8lPsc8ZmfpoA3eKFNsx-Mjw248BhuhHqG7qHNysbdU-F-XrkOGo3YTQwo_EmnFT6UNvsNruFcn6okkPOiIxlKJmLk2LIvkaO0WyTCq59vMJ6tIlDxOzJ_DUO9u_tfNmC213nlnpcqqlezw7YQ-y9wa79U3WJZD1qtQpEjsxemMHi0Y0HCdcdmdI2cj_KZVU4wNbTwniRJjaedAuXTxfkcRTIXnNiSbnMkBSPEzUZx1IyIxxs4W5kOXz_37e3q20ly84pbFHSPzusFXi4KPB2MBtOIHR6RUNRDR7CNoYSy8N3IeTEp2i_D1PeQ9PeUID86etjw9Q4o9neERWYpGHspav8FebK-yLVFG44itrY4_dd8p_l38x8H18lgIAAA==)works the same way... So I don't really understand.

This would be a more honest representation of what is going on: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE32STUvDQBCG_8qwCCZYW-3BQ5oExLsIgpeuhyQ7tYvJ7LI7KUqa_y67af2gxUMOM-_O1_NmEBvdohfZehBUdSgycW-tmAn-tCHwO2wZxUx407smZHLfOG25lCRZd9Y4hgfTWdg408HlfBGC-VR2uQqPwtciw65qe4QCLjxXjMn6NQ3yQWxMT4wOCrhZScoXP0PoqXJIDLEqgyG2GUFSvnVRz-P4mC6O6mJS6p7ZEBhqWt28F0OSQlFOT-e299vk6uowOB3jQfdKgWbswgpTcSlJzERnlN5oVCJj1-M4-4YVZv9PK6YyY1kb8uB6Ql8Msctxy19AA4rhh1StSVV1i0kKY4itM9YnR26bnprQFTwyo0tSGCJvPntg9GI8R_x2uTwY9Yd7rvQOPH-2WEhRG6fQZbC0H6Aqv0UFDtUKbKWUprcM7uzHCrrKvWm6rg2z6WJOilJSgGQomPgSNsu-T9zvQYpHw_CMLMWY18HRE9em88byGadfbWoVO_xyKV8ovStPvXodvwA3qDvS5AIAAA==)

Svelte 5 is now able to deeply react to deep nested changes including array#push, slice, etc. without doing any kind of copy, deep clone, etc.

With this capacity, it's able to ensure a component that receives a value is never mutated from within that component unless it receives the value using `bind:` 

Right now I don't see any way to tell if a variable has been passed using bind or not. It doesn't appear documented either. I think I will open an issue at svelte

**Comment by mskocik** [comment]
> Right now I don't see any way to tell if a variable has been passed using bind or not. It doesn't appear documented either. I think I will open an issue at svelte

👍 Yes, I came to the same conclusion, that it's impossible to find out.

Your example is definitely better, but Svelecte has the same problem also with 'single' item value, but maybe that's because of mix rune and non-rune mode.

**Comment by jamesst20** [comment]
> > Right now I don't see any way to tell if a variable has been passed using bind or not. It doesn't appear documented either. I think I will open an issue at svelte
> 
> 👍 Yes, I came to the same conclusion, that it's impossible to find out.
> 
> Your example is definitely better, but Svelecte has the same problem also with 'single' item value, but maybe that's because of mix rune and non-rune mode.

I have opened an issue at Svelte in case you want to follow: https://github.com/sveltejs/svelte/issues/11672
