### ISSUE TITLE
Make $selected non enumerable

### ISSUE THREAD

**Issue by jamesst20** [mskocik/svelecte#232]
Hi,

When I use `valueAsObject={true}` I end up having `$selected: true` in my payload.

This could be fixed by marking the property as non enumerable.

```javascript
if (!Object.prototype.hasOwnProperty.call(item, "$selected")) {
  Object.defineProperty(item, "$selected", { enumerable: false, writable: true });
}
```

Could this be done? :)

v5.0.0-next.6

**Comment by mskocik** [comment]
This seems to be still broken as mentioned in #233
