### ISSUE TITLE
Bug: Svelecte use the wrong labelField with valueAsObject

### ISSUE THREAD

**Issue by jamesst20** [mskocik/svelecte#233]
**Exemple**

```javascript
  const datas = [
    { id: 1, tag: "Tag 1", type: "Product" },
    { id: 2, tag: "Tag 2", type: "Product" },
    { id: 3, tag: "Tag 3", type: "Food" },
    { id: 4, tag: "Tag 4", type: "Food" },
  ];

  let values = $state([datas[0], datas[1]]);
```

```
<Svelecte
  bind:value={values}
  labelField={"label"}
  multiple={true}
  options={datas.map((data) => ({ ...data, label: `${data.type}: ${data.tag}` }))}
  valueAsObject={true}
  valueField={"id"}
/>
```

On render, every selected data will render with "undefined" text, however if I pick new items, they display just fine. It seems on render Svelecte pick up the text from the values instead of the option.

```
5.0.0-next.7
```

**Proof**

Using an existing field that I override in options:

```
<Svelecte
  bind:value={values}
  labelField={"type"}
  multiple={true}
  options={datas.map((data) => ({ ...data, type: `${data.type}: ${data.tag}` }))}
  valueAsObject={true}
  valueField={"id"}
/>
```

On page load the "type" is displayed, when I select an item  it is properly formatted to `${data.type}: ${data.tag}`

**Comment by mskocik** [comment]
Your example is confusing - you define `values` which don't have _customized_ `label`/`type` property.

This is [my (updated) version](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACo1Sy2rDMBD8lUUEkoBxmjYnJy7tpdcW2pttiGIpQa0sCWvdB8b_Xq3yIKEt9KYZzcw-pJ5tlZaeZUXPDG8ky9i9cyxh-OUI-HepUQbsbdfWxKx83SqHt6UBUI2zLcJzEMkaJWxb28DYH-CdkZ84XpamRBLX1ngEwZF7yKEA4gB6UCKDeQLIdxmU7IXvYF6ygEMDRDy1VnQ1lgyG5NxyfWG5_o_l5sJyc255sFb80C8u9Is_9VWcUUuEhjsnRRgvjpkGOJnQcQr5LUx6SNOUYAKab6TOYD3qCacUO2RwRHw3rGGYTin3kPzOdSdpcSOPHOWk2JcqrqrkULWYV9V0CTCbgbBmjPBh2zeyB-Ii4XfrkuYmszIKFdfg4ysqa87igBpazU5fIIDj49MiNsqILNbJ-325geim06icjhLrKNLn_b5yvI_Se_-4eQ1BJ-JBSS3yvmQqbDrq4tJOdETxZhY6CV-0sUJtlRQsw7aTQzV8A6uf6TXdAgAA). But it's completely broken 🤯. Haven't tried it yet to run locally on the older svelte 5 version. 

Which svelte 5 version are you on?

**Comment by jamesst20** [comment]
Crap this is my mistake. I always forget that my wrapper around Svelecte magically do strictMode={!valueAsObject} to avoid this kind of confusion. I was confused myself for the past 30 minutes as I use everything in its latest version.

Very sorry for the wasted time.

By the way, it seems your $selected fix don't work so I added a demo aswell

Here is a proper REPL to replicate the issue: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE41R0WobMRD8lUUYcobrxXZSChefaV7yUGhTcN4sQ-TT-qpWJwlpz9SI-_eiOzuJKYG8aUYzw85uZHulMbByE5kRLbKS3TvHckZHl0A4oCZkOQu283VilqH2ytGKGwDVOusJ1gfUWBPC3tsWrsIJfv1czIrZJ4N_qfhydccNp2SqrQkEUpAIUMEGEgcQQckS5jmQaErg7Ek0MOcshzRIIn56K7uaOIM-f2tZXFgWH7HcXFhu3loerJX_6W8v9Lfv6renjpw0ErTCOZRQjVWLVrgsS88pVCvIIhRFkWAOWuxQl_A8iQkXKbov4YxE0z9DP52m7FPyQegO0_ImgQRhtomnrLCZbfscXuF822_PzokywWFNGWfr8UByTEp9xsgkXV6_HJib5fm0qd5OGVkOwiqO-j7RbadJOT1IrCNlTajiWH74H6T34XH3G-thOYG8qum7lVjFvdABX2UPCrWsImdKcjbQw3Je6AENP9fDfNwsnUcIdNRYcbYT9Z_G287IErRqflHjxfGOs9W5cMlN_LZ-_FGkGUyj9sdsbJKD6bTOYTHt0wqcxxXLWWul2iuUrCTfYb_t_wGY1PCILwMAAA==)

**Comment by mskocik** [comment]
> to avoid this kind of confusion. 

This is funny that even I got confused 😆 - but I should know as component author, right?

Honestly I didn't "check" the correctness of the fix, I expect it will work. Will fix it properly this time. Thanks for bringing these issues to the light.

EDIT: sorry I edited your comment instead of quoting it - fixed 😆

**Comment by mskocik** [comment]
Okay... the `$selected` property issue is still here, but is this "labelField" issue valid? I can't reproduce it 🙄

**Comment by jamesst20** [comment]
> Okay... the `$selected` property issue is still here, but is this "labelField" issue valid? I can't reproduce it 🙄

You don't see "Undefined" ?

[REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE41R0WobMRD8lUUYcobrxXZSChefaV7yUGhTcN4sQ-TT-qpWJwlpz9SI-_eiOzuJKYG8aUYzw85uZHulMbByE5kRLbKS3TvHckZHl0A4oCZkOQu283VilqH2ytGKGwDVOusJ1gfUWBPC3tsWrsIJfv1czIrZJ4N_qfhydccNp2SqrQkEUpAIUMEGEgcQQckS5jmQaErg7Ek0MOcshzRIIn56K7uaOIM-f2tZXFgWH7HcXFhu3loerJX_6W8v9Lfv6renjpw0ErTCOZRQjVWLVrgsS88pVCvIIhRFkWAOWuxQl_A8iQkXKbov4YxE0z9DP52m7FPyQegO0_ImgQRhtomnrLCZbfscXuF822_PzokywWFNGWfr8UByTEp9xsgkXV6_HJib5fm0qd5OGVkOwiqO-j7RbadJOT1IrCNlTajiWH74H6T34XH3G-thOYG8qum7lVjFvdABX2UPCrWsImdKcjbQw3Je6AENP9fDfNwsnUcIdNRYcbYT9Z_G287IErRqflHjxfGOs9W5cMlN_LZ-_FGkGUyj9sdsbJKD6bTOYTHt0wqcxxXLWWul2iuUrCTfYb_t_wGY1PCILwMAAA==)

Displayed options should be taken from the `options` array and not the values itself no?

![Capture d’écran, le 2024-06-04 à 14 40 25](https://github.com/mskocik/svelecte/assets/490234/897055ca-232a-40fb-8b3c-04f966d355b8)


I would be expecting Svelecte to cross match my values with options to know what to display using the `valueField`

Edit:

In my use case, i'm creating Product Collections that are based on product tags. When I go to my edit page of Product Collections, `/product_collections/:id/edit` I receive by the backend the existing product collection and all the product tags.

Backend:
```
product_tags = [ { id: 1, tag: "Tag 1", type: "Product" }, ... ]
product_collection= {
  id: 1,
  product_tags: [
    { id: 1, tag: "Tag 1", type: "Product" },
    ...
  ]
}
```

I use Svelecte to update `product_collection.product_tags` however the label in the dropdown is not something that is "persisted" in the database, hence why i'm customizing the options. Also the options come from `product_tags` and not the product_collection itself as it is only containing a very few selected tags

**Comment by mskocik** [comment]
> Displayed options should be taken from the `options` array and not the values itself no?

Yes, in general. BUT you are in `valueAsObject` mode AND providing initial value (`strictMode={false}`). Therefore it doesn't really use "options" version of given object, but the initial one.

_Why is it done this way?_ you may ask and that's because it allows you to set initial selection object which is not present in options.

---

💡 Your use case has a very simple solution - define your own render function, which will return desired label: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACo1UXWvbMBT9KxdRqFM8J_0YA7cO7UsfBlvHurc4UNmSHW2KZKTrbkH4v0-S4zTZGOzJOfeee3TukYgjjZDcknzliKJbTnLy0HUkJbjrArCvXCL32Ore1KFyZ2sjOlyWCkBsO20Qnj2J18ihMXoL53YP799ni2zxTvFfmH04vy1ViWGo1soiMIrUQgErCDUAB4LlcJkC0jaHknyjLVyWxGNvJBS-GM36GksCQ3o8cnUycvU_I9cnI9fHI49as7_4Nyf8m3_y1_sdS5QcYUu7jjO_Ylw18zBJws8ZFEtIHGRZFmAKklZc5vBy5gLOgvSQw4RoO7zAMJsF7b3yK5U9D-GdWaTIk5Xba9nVYj2k8AYv18N6mjwTynb-XpKSPI8XxEalsM8oOVHnFxfhAxfwlSvGDTcgLOCGg_VvBBptwEYJoRVQxYAZ3TH9U6VQ9Qg73UNNFTBhUai2F3YDFbUcPFvYw-EdNV4NuYlZTyfexzI4XX33tAF0h390Kq3lcCQ0tufh0_RqNBUzncwnXiM9GpiBixeFhmNvVEjeM96CjyDkHlhDqe7mhzfvwfTag-tKKJbH7Ao3RjiE8raXKDoZKV7MG7KFG99D7Efqg32KK4ZDzN5p4U6MD6Fn0YgaP2nmz2iotPxN4lFwyQpXEuEfYSzH8UM5otiZR-_efWf8JeJO8qIkFa1_tEb3fgeQot1ga-jutiTLKai8VO7j89PnLHhQrWh2ybhlCqqXMoWrWYzHiy79f8RWM9EIzkiOpufDevgNWzW-8V4EAAA=)

**Comment by jamesst20** [comment]
> > Displayed options should be taken from the `options` array and not the values itself no?
> 
> Yes, in general. BUT you are in `valueAsObject` mode AND providing initial value (`strictMode={false}`). Therefore it doesn't really use "options" version of given object, but the initial one.
> 
> _Why is it done this way?_ you may ask and that's because it allows you to set initial selection object which is not present in options.
> 
> 💡 Your use case has a very simple solution - define your own render function, which will return desired label: [REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAACo1UXWvbMBT9KxdRqFM8J_0YA7cO7UsfBlvHurc4UNmSHW2KZKTrbkH4v0-S4zTZGOzJOfeee3TukYgjjZDcknzliKJbTnLy0HUkJbjrArCvXCL32Ore1KFyZ2sjOlyWCkBsO20Qnj2J18ihMXoL53YP799ni2zxTvFfmH04vy1ViWGo1soiMIrUQgErCDUAB4LlcJkC0jaHknyjLVyWxGNvJBS-GM36GksCQ3o8cnUycvU_I9cnI9fHI49as7_4Nyf8m3_y1_sdS5QcYUu7jjO_Ylw18zBJws8ZFEtIHGRZFmAKklZc5vBy5gLOgvSQw4RoO7zAMJsF7b3yK5U9D-GdWaTIk5Xba9nVYj2k8AYv18N6mjwTynb-XpKSPI8XxEalsM8oOVHnFxfhAxfwlSvGDTcgLOCGg_VvBBptwEYJoRVQxYAZ3TH9U6VQ9Qg73UNNFTBhUai2F3YDFbUcPFvYw-EdNV4NuYlZTyfexzI4XX33tAF0h390Kq3lcCQ0tufh0_RqNBUzncwnXiM9GpiBixeFhmNvVEjeM96CjyDkHlhDqe7mhzfvwfTag-tKKJbH7Ao3RjiE8raXKDoZKV7MG7KFG99D7Efqg32KK4ZDzN5p4U6MD6Fn0YgaP2nmz2iotPxN4lFwyQpXEuEfYSzH8UM5otiZR-_efWf8JeJO8qIkFa1_tEb3fgeQot1ga-jutiTLKai8VO7j89PnLHhQrWh2ybhlCqqXMoWrWYzHiy79f8RWM9EIzkiOpufDevgNWzW-8V4EAAA=)

Thanks for the explanation! I will use the renderer then :)

From my perspective, the only thing that should differ between `valueAsObject` true or false is that in one scenario it expect values to be `option[valueField]` and the other `option` itself. `strictMode` should always behave the same, thus checking for the presence of `valueField` in the options when enabled.

Feel free to close if you believe the current behavior is the expected one :)

**Comment by mskocik** [comment]
@jamesst20 Of course you are right. I got it messed up in my head with `strictMode`. I don't use objects as value very often. So to clarify: you don't need to use `strictMode={false}` in your use case.

Setting `strictMode={false}` is required only when following conditions (all at the same time) are met:
- use `valueAsObject`
- use `fetch`
- need to set initial value.

**Comment by mskocik** [comment]
Btw I still consider render function to be better approach than adding property `label` to options.

**Comment by jamesst20** [comment]
> @jamesst20 Of course you are right. I got it messed up in my head with `strictMode`. I don't use objects as value very often. So to clarify: you don't need to use `strictMode={false}` in your use case.
> 
> Setting `strictMode={false}` is required only when following conditions (all at the same time) are met:
> 
> * use `valueAsObject`
> * use `fetch`
> * need to set initial value.

Thanks! version next.9 indeed solves properly the issue if strictMode is enabled! $selected is also gone.

Same REPL as before but now working

[REPL](https://svelte-5-preview.vercel.app/#H4sIAAAAAAAAE41RwWobMRT8lYcwZA3qxnaSQzde01xy6KEpuDfLEHn1vFGqlYT01tQs--9Fu7YbUwq9aebNDG_0OrbXBiMrNh2zskFWsCfvGWd09AnEAxpCxll0bagSs4xV0J5WwgLoxrtAsD6gwYoQ9sE1cBNP8MtDPstnnyz-ovzzzaOwgpKpcjYSKEkyQgkbSBxAB1oVMOdAsi5AsB-yhrlgHNIiifgenGorEgx6_tGyuLIs_sdyd2W5-2h5dk79pb-_0t__U789dRRkkKCR3qOCcqyaN9JnWXpOoVxB1kGe5wlyMHKHpoDXSZdwnqL7As5I1v0r9NNpyj4lH6RpMX3eJJIkzDbdKStuZtuewx843_bbs3OibfRYUSbYejyQGpNSnzEySZe3lwMLuzyfNtXbaauKQVh2o75PdNMa0t4MEudJOxvLbiw_zAfpU3zZvWNFF-JZo1FlJ5hWgg264Rsu9ICGye2wibBLHxAiHQ2Wgu1k9bMOrrWqAKPrN6qDPD4KtjpXK4Ttvq5fvuWRgra13h-zcWcOtjWGw2Lap7I-4Ipx1jil9xoVKyi02G_732HqRQsZAwAA)

I agree that the renderer function is a better approach as I don't need to strip out my custom label from the payload prior sending to the server. This is what I am using but I am glad this could lead to some bug fixes.

Is it normal that it doesn't work with strictMode disabled? It's the expected behavior?

**Comment by mskocik** [comment]
> Is it normal that it doesn't work with strictMode disabled? It's the expected behavior?

I am not sure I follow now. If you are refering to this previous comment 👇 I fixed it as you described it should work. If you are talking about something else, please explain more, I am lost at the moment :)

> From my perspective, the only thing that should differ between valueAsObject true or false is that in one scenario it expect values to be option[valueField] and the other option itself. strictMode should always behave the same, thus checking for the presence of valueField in the options when enabled.
