### ISSUE TITLE
Height changes when focused or selected option

### ISSUE THREAD

**Issue by galaczi** [mskocik/svelecte#236]
I am using Svelecte with Tailwind. When I click on the search field, it seems like padding is added, the size of the input increases. Once I select an option, it increases even further. This causes a layout shift on the whole page.

I did not change any styling. My guess is that Tailwind does a reset by default, and you might be counting on some kind of default browser style to be present for the size to be consistent.

**Comment by mskocik** [comment]
I fixed it for `svelecte@next` version. If you are using v4 you will need to set `--sv-min-height` and/or tweak `--sv-item-wrap-padding` CSS property.

**Comment by galaczi** [comment]
Great, thank you! Btw, if you would use ``em`` for sizing, everything would adjust automatically and would be consistent. Just a wild idea.
