### ISSUE TITLE
max on creatable

### ISSUE THREAD

**Issue by anatoliy-t7** [mskocik/svelecte#238]
Hello. 

How do I can control `max` for `creatable` items?

Thank you for the great component.

**Comment by mskocik** [comment]
`max` controls amount of _selected options_. There is no limit how many items can user create. It's irrelevant, because only selectied items matters (from components' point of view)

Does it answer your question?

**Comment by anatoliy-t7** [comment]
Yes. Thank you. I need to find a way to limit of created items.

**Comment by mskocik** [comment]
You can use your own `createHandler` and internally count number of created items. And throw an error when new item shouldn't be created.

**Comment by anatoliy-t7** [comment]
I did it. But it is still added in DOM but not in value.
```javascript
function onCreateOption(option: { value: any }) {
	if (value.length < max) {
		value.push(option.value);

		value = value;
	}
}
```

**Comment by mskocik** [comment]
Actually you want to do something like in this [REPL](https://svelte.dev/repl/61e22d52f850460ba4f5e80de4d8345e?version=4.2.18):

- specify `createHandler` and throw an error when you want to avoid creating additional item.
- handle `createFail` event as you like.

I found some issues with related code, so update to the latest `4.2.3` stable version. If you are using `svelecte@next`, I will update it in a minute...
