### ISSUE TITLE
Wrong nomatch message for multiple selection 

### ISSUE THREAD

**Issue by msksk** [mskocik/svelecte#243]
In multiple selection, when you selected all the items, it will show `config.i18n.empty` 'No Items'.
This topic was mentioned 3 years ago in #16.

I found it still shows `config.i18n.nomatch` 'No matching options'.

<img src="https://github.com/user-attachments/assets/8708fc67-e05f-456d-a333-26593de23384" width="50%">

You can see the message in https://svelecte.vercel.app/searching

---
This can be fixed by replacing update condition in
https://github.com/mskocik/svelecte/blob/968dfec660698e559ce45b7b824cd53771218a4f/src/lib/Svelecte.svelte#L660
with `options_filtered.length !== options_flat.length && selectedOptions.length !== options_flat.length`.

**Comment by mskocik** [comment]
Thanks for reporting, I missed this use case in the test suite. Fixed now
