### ISSUE TITLE
Svelte 5: Drag & Drop is broken

### ISSUE THREAD

**Issue by jamesst20** [mskocik/svelecte#245]
See the exemple here: https://svelecte-v5.vercel.app/examples#drag--drop

Everything works, events are triggered but options are not updated

**Comment by jamesst20** [comment]
Any news on this @mskocik  don't mean to put up any pressure just asking

**Comment by mskocik** [comment]
hey! thanks for reminding me 😄 I was busy with work... Will take a look now.

**Comment by jamesst20** [comment]
Thanks @mskocik !
