### ISSUE TITLE
Expose onClick event of the selection items

### ISSUE THREAD

**Issue by ZreXoc** [mskocik/svelecte#248]
First of all, thank you for the awsome multiselect plugin! But I met some problem when trying to listen onClick event of the selection items.

I have a search option that users can decide what fields the results are sorted by. And I want to switch the descending and ascending by clicking the select item. Here's the REPL example:
https://svelte.dev/repl/34a30e539734436a9f3ea1e247b1759d?version=4.2.18

I tried slot but it that means I have to maintain the style and drag & drop myself. `on:mousedown`can't tell if you're dragging or clicking, and unavailable for mobile device.

Is it possible to expose the click event just like `on:mousedown` but with the value/index of the clicked selection item as argument?

**Comment by mskocik** [comment]
Actually you don't need `click` event exposed.

Let's take a look at my [REPL](https://svelte.dev/repl/13d31501653845b983e4d512780b6d3b?version=4.2.18). Here I add _wrapper_ `<div>` with action, which hooks event listener to it. It intercepts every click and based on `data-*` attribute of selected option it performs your desired action. I use `{ capture: true }` as option to avoid opening svelecte's dropdown on "sort" item.

Note: setting value for `data-reverse` attribute is silly, but enough for demonstration purposes.

**Comment by ZreXoc** [comment]
> Actually you don't need `click` event exposed.
> 
> Let's take a look at my [REPL](https://svelte.dev/repl/13d31501653845b983e4d512780b6d3b?version=4.2.18). Here I add _wrapper_ `<div>` with action, which hooks event listener to it. It intercepts every click and based on `data-*` attribute of selected option it performs your desired action. I use `{ capture: true }` as option to avoid opening svelecte's dropdown on "sort" item.
> 
> Note: setting value for `data-reverse` attribute is silly, but enough for demonstration purposes.

Thank you for your detailed reply and REPL, it's quite helpful
