### ISSUE TITLE
compiler warnings: declared in a module script and will not be reactive

### ISSUE THREAD

**Issue by kamholz** [mskocik/svelecte#25]
When bundling `svelecte` in a SvelteKit app, I get a bunch of compiler warnings:

```
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:213:6 "config" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:215:8 "config" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:217:10 "config" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:218:10 "config" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:220:65 "formatterList" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:220:92 "formatterList" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:242:21 "fieldInit" is declared in a module script and will not be reactive
[vite-plugin-svelte] .../node_modules/svelecte/src/Svelecte.svelte:243:21 "fieldInit" is declared in a module script and will not be reactive
```

As far as I can tell, none of these warnings are actually significant because these variables don't need to be reactive, but it would be nice to eliminate the warnings somehow. I'm not sure if the best solution is to add a "svelte-ignore module-script-reactive-declaration" comment (does that work in JS code??), to move the imports out of the module context, or something else.

**Comment by mskocik** [comment]
This one is how rollup-svelte plugin works... It's quite annoying and I am not sure if the comment solution works. It didn't work few months ago.
Anyway it's not related component function, because module props are not used in reactive way.

Will check if this one has changed lately, I know more people was having the same issue with this warning.
