### ISSUE TITLE
Store values in on:change handler give 'store.subscribe is not a function'

### ISSUE THREAD

**Issue by EniacMlezi** [mskocik/svelecte#252]
It seems like store functions get wiped somewhere before the `on:change` handler is reached. Check this [REPL](https://svelte.dev/repl/b3ab9e87a7424eb39147045adf825997?version=4.2.19).

Are Stores (and passing functions in general) not supported?

**Comment by mskocik** [comment]
Functions are unexpected, just simple objects should be in `options` array. Svelecte creates internal copy it anyway. 
If you change `options` but still keep the same `valueField` property, I think it should work
