### ISSUE TITLE
Make list dropdown a top-level DOM element

### ISSUE THREAD

**Issue by mhkeller** [mskocik/svelecte#258]
In my use case, I have the Svelect component in an element with `overflow: scroll`. Unlike a native `<select>` element, the Svelect list gets cut off within the scrollable element. It would be nice if the dropdown list were on top of every element – either through `position: absolute;` or `position: fixed`. You may be able to leverage the new [`position-anchor`](https://developer.mozilla.org/en-US/docs/Web/CSS/position-anchor) CSS property to do this without JavaScript.

**Comment by mskocik** [comment]
Definitely can be useful, but comes with the need to correctly position dropdown afterwards. Unfortunately not all browsers support `position-anchor` at the moment

**Comment by mhkeller** [comment]
Thanks for adding this. Do you have a brief example of how to use this function and what it needs to be set to?

**Comment by mskocik** [comment]
Very basic [example](https://svelte.dev/repl/941cb416ca83429fa88dc5f0cee87a81?version=4.2.19). Basically it's custom action, you can you to modify DOM position of your dropdown, etc. 
Depending on your page layout it may require more work and may be practical to use something like @floating-ui library for that.
