### ISSUE TITLE
RangeError: Maximum call stack size exceeded in list.js

### ISSUE THREAD

**Issue by jieter** [mskocik/svelecte#26]
I'm looking into using svelecte in my application. In one of the use cases, the selection of a location can also be made trough a Leaflet map, simplified code looks like this:

```JavaScript
let selectedLocation;
<Svelecte fetch={api.searchLocation} bind:selection={selectedLocation} />

function onMapClick(e) {
     api.getLocation(e.point).then((location) => {
         selectedLocation = location;
     }
}
```
After clicking the map, the Svelecte instance correctly has the location name:

<img width="385" alt="Screenshot 2021-07-27 at 12 54 06" src="https://user-images.githubusercontent.com/1470389/127142697-1a079121-f825-4100-bcaa-c3a97bf9641f.png">

Now, if I focus the Svelecte instance, and hit 'home', I get this error in my console, hitting home again will result in the same message.

```
Uncaught RangeError: Maximum call stack size exceeded
    at Object.next (list.js:122)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
    at Object.next (list.js:127)
...
```

**Comment by mskocik** [comment]
Will look into it.

**Comment by jieter** [comment]
Great, I'll check it tomorrow

**Comment by jieter** [comment]
I just tested it, it works like expected with 1.3.4, thanks!
