### ISSUE TITLE
v5: selection snippet is rendered even when nothing is selected in multiple selection

### ISSUE THREAD

**Issue by msksk** [mskocik/svelecte#266]
You can see in the v5  documentation site. It causes conflict with placeholder.
![image](https://github.com/user-attachments/assets/400881d5-1c24-4cf5-988e-eb15458d2f09)

It does not occur in v4.
![image](https://github.com/user-attachments/assets/75b734aa-957f-41e9-89dd-318f4ae4fa97)

We can simply avoid it just by making template enclosed by `{#if selectedOptions.length > 0} ... {/if}`, but it would be a little confusing for migration from v4 to v5.

**Comment by mskocik** [comment]
You are right, that the conditions which snippet should render has been changed slightly. I think it's ok. Maybe I will revert it to v4 variant. Thanks for pointing out

**Comment by mskocik** [comment]
I reverted it to match v4 behavior
