### ISSUE TITLE
Createable option does not add the new option when multiple=false

### ISSUE THREAD

**Issue by gerhardcit** [mskocik/svelecte#267]
I have a form that lookup streets that was previously entered. If not found, I want to add it.
This worked fine in v4. But in v5 the only way to get it working is to add a `onCreateOption`
```typescript
const handleCreateOption = async (option: any) => {
    console.log('handleCreateOption', option.value);
    $formData.address.streetName = option.value;   // have to force this for form to be updated
};
```

```html
<Form.Field {form} name="address.streetName" class="col-span-2">
  <Form.Control>
	  {#snippet children({ props })}
		  <Form.Label>Street/Building Name</Form.Label>
		  <Svelecte
			  onCreateOption={handleCreateOption}
			  fetch="/api/lookup/streets?search=[query]"
			  minQuery={2}
			  creatable={true}
			  keepCreated={true}
			  creatablePrefix=""
			  allowEditing={true}
			  valueField="value"
			  labelField="value"
			  placeholder="Select street"
			  strictMode={false}
			  bind:value={$formData.address.streetName}
		  />
		  val:{$formData.address.streetName}
	  {/snippet}
  </Form.Control>
  <Form.FieldErrors />
</Form.Field>
```

the example https://svelecte-v5.vercel.app/validation only deals with multiple selections.

the api returns an array:  [{value: 'street1'}, {value:'street2'}

it seems to work ok with multiple={true} I have not tested that so much because the form validation fails as it expects a string.

**Comment by mskocik** [comment]
This is probably a bug 🤔 I am currently rewriting component to use runes. I will include it in testing.

**Comment by mskocik** [comment]
Can you try to add property `name`? Because only when `name` is specified data of underlying select are sent in POST request.

**Comment by mskocik** [comment]
This is not an issue (at least with the latest release). I've also updated the example on form validation page. Check it out. If your issue persists, let me know
