### ISSUE TITLE
Mutating state when using bind:value together with multiple prop does not update the component

### ISSUE THREAD

**Issue by jochienabuurs** [mskocik/svelecte#272]
I've created a REPL to showcase the behavior.

https://svelte.dev/playground/7d57062c8ca24dd589e486f38eec92ef?version=5.14.2

I would expect the selected options to be cleared when pressing the erase button.
The state gets reset but the svelecte UI does not reflect that.

Am I missing something here?

**Comment by mskocik** [comment]
What an unbelievable bug! Will fix it tomorrow ASAP. Must be some issue with infinite loop guard, when comparing array values. In single select works correctly.

**Comment by jochienabuurs** [comment]
Yeah, in single select it works like a charm.

Could it be that this was working in 5.0.0@next-xxx as I've used it extensively but never noticed it until i migrated to v5.0.0 just a few days ago.

**Comment by mskocik** [comment]
The funny thing is I had code in place. It was just commented out, because in the meantime I forgot why it was required. Now I know 😆
