### ISSUE TITLE
Responsiveness with bootstrap5

### ISSUE THREAD

**Issue by jieter** [mskocik/svelecte#28]
Svelecte doesn't seem to handle resizing correctly in a bootstrap5-styled document.

Expected rendering:
<img width="1078" alt="Screenshot 2021-08-18 at 14 02 25" src="https://user-images.githubusercontent.com/1470389/129894744-33c1caa1-a270-41f2-a155-f1ca8d9db184.png">

After resizing below the breakpoint collapsing the menu and again to a wider window:

<img width="1061" alt="Screenshot 2021-08-18 at 14 03 16" src="https://user-images.githubusercontent.com/1470389/129894851-f74f7584-8827-4fc8-a172-355b4c83ad09.png">

demo: https://jieter.github.io/orc-data/site/#extremes

**Comment by mskocik** [comment]
@jieter Can you update to version 1.3.6? Possibly the same issue as mentioned in #29

**Comment by jieter** [comment]
I updated in https://github.com/jieter/orc-data/commit/488b1c654581d5cf5a38bcedc547b8665779720c, which is now live on the above url. Bug is still present unfortunately.

**Comment by mskocik** [comment]
It found the cause! It's a bug in your app. Dropdown indicator's `width` and `height` attributes are changed on resize. Scaning through your code, it can be here:

```js
/** polarplot.js */
plot.resize = function () {
  if (width() === previousWidth) {
    return;
  }
  // 👇 selects first svg, which is svelecte dropdown arrow
  select('svg').attr('width', width()).attr('height', height()); 

  // rest of function
}

**Comment by jieter** [comment]
🤦‍♂️ 

Thanks!

**Comment by jieter** [comment]
That was indeed the culprit, fixed now.
