### ISSUE TITLE
New created item, cannot modify directly. Must clear item first

### ISSUE THREAD

**Issue by niwasmala** [mskocik/svelecte#30]
Thanks alot for creating awesome Svelecte!

**Problem**
When I use creatable options, it works perfectly on creating new item. But when I want to edit the created item, e.g fixing typo, I have to clear the item and type from empty first.

**Step to Reproduce**
1. Open https://mskocik.github.io/svelecte-docs/?ref=madewithsvelte.com#custom-element , use color options, and check creatable

2. Type "New Colour" and enter

![image](https://user-images.githubusercontent.com/476869/135015473-f56a1a84-ca30-4861-87df-7f9d826a128d.png)

3. Change "New Colour" to "New Colour 2". Click element, options displayed. Cannot directly add " 2"

![image](https://user-images.githubusercontent.com/476869/135015594-7ed46cb9-e788-4739-aa03-2f24fd72c89f.png)

Is there any way to change directly without clearing the input? Thank you.

**Comment by mskocik** [comment]
There is no way to edit already created item at the moment. That would require some updates in internal logic.

@niwasmala It's clearly visible with multiple select, that selected option is not editable.
