### ISSUE TITLE
Svelecte crashes when using `virtualList={true}`

### ISSUE THREAD

**Issue by jieter** [mskocik/svelecte#35]
Known good version: 1.3.7
Tested broken versions: 1.4.0, 2.0.0

The snippet below works without `virtualList={true}` (albeit very slow, which is to be expected), but crashes with `virtualList={true}`.

```
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'firstElementChild')
    at virtualListDimensionsResolver (Dropdown.svelte:108)
```

```
<Svelecte
        {options}
        placeholder="Sailnumber, name or type"
        virtualList={true}
        bind:selection
/>
```
([source](https://github.com/jieter/orc-data/blob/23c8f64f66e617151df37154e162cc8bee75a41d/site/src/components/BoatSelect.svelte#L25-L29))

**Comment by mskocik** [comment]
I noticed it today too. Must be due internal changes in svelte itself (I am using 3.41.1 version since v1.4)

@jieter test fix for yourself, should work. At least works for my dev version.

**Comment by jieter** [comment]
Just tested with svelecte@2.1.0, works as expected again.

The internal changes in svelte breaking svelecte sound a bit concerning to me, it would be nice if there was a way to catch these in tests. Did you consider adding those?

**Comment by mskocik** [comment]
Yes @jieter, you are right, it doesn't feel like rock solid certainty. It's due to internal _"auto guessing/computing"_ of required properties for virtual list. If you specify `vlHeight` and `vlItemSize` properties, you have nothing to worry about.

Tests would be great addition, thanks for reminder 👍
