### ISSUE TITLE
Svelecte with an initial value bound with `bind:value={value}` sets the value to `null`

### ISSUE THREAD

**Issue by jieter** [mskocik/svelecte#39]
When I bind a variable with an initial value to a Svelecte component using `bind:value={value}`, the value is updated to `null` before it's updated to the original value again. These seem to be unnecessary updates, can they be avoided somehow?

In my use case, there are more field, thus resulting in even more unnecessary updates.
 
Example:
```
const items = [{'value': 1}, {'value': 3}];
const options = [
    {id: 1, value: 'a'},
    {id: 2, value: 'b'},
    {id: 3, value: 'c'},
    {id: 4, value: 'd'},
];

$: console.log(JSON.stringify(items));
</script>
{#each items as item}
    <Svelecte {options} bind:value={item.value} valueField="id" />
{/each}
```
console output:
```
[{"value":1},{"value":3}]
[{"value":null},{"value":null}]
[{"value":1},{"value":3}]
```

**Comment by mskocik** [comment]
When tested now, console.log is executed only once. Thanks for reporting this  one, it was a great opportunity to refactor some internal logic.

**Comment by jieter** [comment]
Great, thanks for the fix!
