### ISSUE TITLE
Drag and Drop items in multiple select

### ISSUE THREAD

**Issue by Amerlander** [mskocik/svelecte#45]
I have a use case where the order of the selection is important.

By now when I have this selection:

![image](https://user-images.githubusercontent.com/3764089/138669930-66310425-d1c8-4ace-939c-b76de626662f.png)

And want to move Croatia in the first position, I have to delete everything before and add it again

![image](https://user-images.githubusercontent.com/3764089/138670102-7798f620-d168-4cb3-8c9e-d272152f120c.png)

Is it possible to implement a drag and drop feature to reorder selected items?

**Comment by mskocik** [comment]
This could be added in next version. I just need to think it a little bit, because I would like to have it only as a _optional_ dependency

**Comment by mskocik** [comment]
Check this [REPL](https://svelte.dev/repl/da2de4b9ed13465d892b678eba07ed99?version=3.44.0) how to set it up.

**Comment by Amerlander** [comment]
great, thats awesome! Thank you!
