### ISSUE TITLE
Feature request: Allow actions on components for e. g. validations within forms/form-libraries

### ISSUE THREAD

**Issue by taffit** [mskocik/svelecte#48]
Hello,

first of all: Thank you for this wonderful library. Works perfectly where other fail and has a lot of settings allowing you to adjust it to your needs.

One thing I'm missing, though, is to attach [Svelte actions](https://svelte.dev/docs#use_action) on the `Svelecte`-component. My use case: I'm using another marvelous library called [`svelte-use-form`](https://github.com/noahsalvi/svelte-use-form) for my forms, as it is lightweight and allows to use the standard-html-tags for forms which can then be enriched by different other libraries.    
Now, as `svelecte` is heavily used in my forms (as it basically *IS* an extended form control) it would be nice to attach actions for the validators. I know the provided `required`-attribute, but this doesn't cooperate with form or validator libraries used for the whole form.    
Allowing to attach such actions would make it easy to integrate it into other form- or validator libraries. A way to implement this would be like [Svelte Material UI](https://sveltematerialui.com/demo/common) does (see `Common` &rarr; `Use Actions`). There you add it basically as property: `<MyComponent use={ MyAction1, [ MyValidatorActionWithParams, { param1: 'val1', param2: 'val2' } ] } />`. This is then applied to the html-tag (in the case of `svelecte`, the `select`- or `input`-tags would probably be the correct target.

As said: thank you once more for this extremely useful library!

**Comment by mskocik** [comment]
Very easy to implement, IF you know which events `svelte-use-form` listens to... Took me a while to figure out, why it was _not_ working, when it was supposed to 😅 

Example repl for you here: 👇 
https://svelte.dev/repl/de3cd8e47feb4d078b6bace8d4cf7b90?version=3.44.1

**Comment by taffit** [comment]
This ... is ... amazing!!! Thank you @mskocik , thanks a lot!   
Not even a day later you already provided the solution, including a perfect REPL! Wow, how responsive and helpful. 👍   
Thank you once more for this marvelous library, it is extremely useful, feature full, configurable ... Just great!

**Comment by mskocik** [comment]
Glad I could help ☺️ Thanks for feature suggestion 👍
