### ISSUE TITLE
web component example

### ISSUE THREAD

**Issue by Selion05** [mskocik/svelecte#61]
Hey, 

I'm looking for a replacement for select2 because it is the only library i use that needs jQuery and Svelecte looks promising. Thanks for that :)

The documentation for the web component didn't work for me (Svelecte was not available on the window object).

Here is a minimal example 

```html
<script src="https://unpkg.com/svelecte/dist/svelecte-element.js"></script>
<script>
    Svelecte.registerSvelecte();
</script>
<!-- options=[{ id: 1, name: 'Item 1' }, { id: 2, name: 'Item 2'}] -->
<el-svelecte name="simple-select" options="&#x5B;&#x7B;&quot;id&quot;&#x3A;1,&quot;name&quot;&#x3A;&quot;Item&#x20;1&quot;&#x7D;,&#x7B;&quot;id&quot;&#x3A;2,&quot;name&quot;&#x3A;&quot;Item&#x20;2&quot;&#x7D;&#x5D;">
```
note the options were just escaped by twig 
```twig
<el-svelecte name="simple-select" options="{{ [{ id: 1, name: 'Item 1' }, { id: 2, name: 'Item 2'}]|json_encode|e('html_attr') }}"></el-svelecte>
```

I'm not to familir with web components but do you thing it's possible to pass the options inside of the element like on a normal select? 

Also I minor thing i noted was  on the Remote (ajax) datasource example that if you e.g type `re` and select one of the colors the other options disappear while you actually might want to select both.

**Comment by mskocik** [comment]
> I'm looking for a replacement for select2 because it is the only library i use that needs jQuery and Svelecte looks promising. Thanks for that :)

Definitely, I created custom-element version exactly for this use-case, because I am using it with PHP myself.
 
> The documentation for the web component didn't work for me (Svelecte was not available on the window object).

There must be something missing or wrong in your html markup. I would need to see the whole template.

You can check [this example](https://jsfiddle.net/em4strqp/) on JSFiddle, where it works.

> I'm not to familir with web components but do you thing it's possible to pass the options inside of the element like on a normal select?

If you pass JSON encoded string as an `options` attribute, it should work

> Also I minor thing i noted was on the Remote (ajax) datasource example that if you e.g type `re` and select one of the colors the other options disappear while you actually might want to select both.

There is option `fetchResetOnBlur` exactly for that. So if you want to reset it for your custom-element, you use:

```html
<el-svelecte fetch-reset-on-blur="false"></el-svelecte>
```

**Comment by Selion05** [comment]
> There must be something missing or wrong in your html markup. I would need to see the whole template.
Sorry for not being clear enough. I was talking about that https://github.com/mskocik/svelecte/blob/d0794392fb1fbd31eea7be3b10cbdc06aa7ba765/docs/index.html#L446 where Sveletect was not available on the window object. 

> If you pass JSON encoded string as an options attribute, it should work
Yeah I saw that, what I meant was if is possible to pass options in more "natural" way for html like so?
```html
<el-svelecte>
  <option value="1">One</option>
  <option value="2" disabled="disabled">Two</option>
  <option value="3" selected="selected">Three</option>
</el-svelecte>
```

**Comment by mskocik** [comment]
>  Sorry for not being clear enough. I was talking about that
> `const { registerSvelecte, addFormatter, config } = window.Svelecte`
>  where Sveletect was not available on the window object.

You must have the script loaded before you try to call it.

As I said before, you must have something wrong in your template, if `window.Svelecte` is undefined and you have svelecte script already loaded.

> Yeah I saw that, what I meant was if is possible to pass options in more "natural" way for html like so?
> 
> ```
> <el-svelecte>
>   <option value="1">One</option>
>   <option value="2" disabled="disabled">Two</option>
>   <option value="3" selected="selected">Three</option>
> </el-svelecte>
> ```

This is not supported at the moment. And the only reason is, that I have never had the need for it. It could be implemented. If you would like this to be add, please open new issue for it.
