### ISSUE TITLE
Initial value for creatable options is not set

### ISSUE THREAD

**Issue by GhaithAlHallak8** [mskocik/svelecte#63]
Hi, I think it's would be nice to have the ability to set an initial value for creatable options in the library.

Example REPL: https://svelte.dev/repl/cdb1ed59493943a19fd255704a68df87?version=3.44.2

**Comment by mskocik** [comment]
Just pass `options` property, like you normally would. If you want the initial values to behave like they were created by user, you need to pass object array, simple array won't be enough.

Like:
```javascript
let opts = [
  {
    value: 'Hello World',
    label: 'Hello World',
    '$created': true  // this property signals, it has been created
  }
]
```

Is it clear?

**Comment by GhaithAlHallak8** [comment]
Thanks!
