### ISSUE TITLE
Component broken on Safari

### ISSUE THREAD

**Issue by rocamalo** [mskocik/svelecte#70]
Just started using this component and everything was smooth, but i'm getting this error on Safari.
TypeError: undefined is not an object (evaluating 'F.focus')

And it breaks my whole website.
Any idea what could it be?
<img width="1342" alt="Screen Shot 2021-12-09 at 15 10 01" src="https://user-images.githubusercontent.com/73503608/145476233-ba412837-4c19-426a-b48d-521367f55c1a.png">

**Comment by mskocik** [comment]
Interesting, I have few questions:

- Can you provide some code snippet how are you actually using svelecte?
- Can you replicate the issuel in svelte REPL?
- Does documentation site works fine for you?
- Are you calling focus method on svelecte?

**Comment by rocamalo** [comment]
Hello and thanks for the reply here is how i am using Svelecte
`{#if allModelOptions && allModelOptions.list.length > 0}

          <Svelecte 
          placeholder="MARCA"
          clearable=true
          options={allMakeOptions} 
          bind:value={selectedMake}
          valueAsObject=true
          >
        </Svelecte>

        {/if}
        </div>
          <div class="select-container">
            {#if true}
            <Svelecte 
            placeholder="MODELO"
            clearable=true
            options={selectableModels} 
            bind:value={selectedModel}
            valueAsObject=true
            on:change="{() => requestSubgroups()}"
            >
          </Svelecte>
          {/if}

        </div>
      
        <div class="select-container">
          {#if true}
          <Svelecte 
          placeholder="PIEZA"
          clearable=true
          options={subGrupos} 
          bind:value={selectedSubgroup}
          valueAsObject=true
          searchable=true
          disabled={!isModelSelected}
          style={!isModelSelected ? "opacity: 0.5;" : ""}
          >
        </Svelecte>
        {/if}
      </div>
    
        <div class="select-container">
          <Svelecte 
          placeholder="AÑO"
          clearable=true
          options={selectableYears} 
          bind:value={selectedYear}
          
          disabled={!isModelSelected}
          style={!isModelSelected ? "opacity: 0.5;" : ""}
          >
        </Svelecte>
        </div>`
I haven't replicate on REPL.
Documentation site works fine.
I believe i'm not calling focus method on svelecte.

Greetings.

**Comment by rocamalo** [comment]
i have this function called when "onChange" on your component, just like i had it with normal selects.

`const requestSubgroups = async ()  => {
      const itemSelect = document.getElementById('subgroup');
      setTimeout(async function(){ const grupos = await getSubgroups(getMakeReadyForRequest(), getModelReadyForRequest());
     console.log(itemSelect);
     subGrupos = grupos;
     subGrupos.unshift({
          id_subgrupo: '',
          nom_subgrupo: 'TODAS'
        });
     console.log(subGrupos); }, 1000);
     
     
   }`

**Comment by mskocik** [comment]
> I believe i'm not calling focus method on svelecte.

Can you make sure of this? Because in given code I see nothing wrong. Should definitely work fine 🤔

**Comment by rocamalo** [comment]
> > I believe i'm not calling focus method on svelecte.
> 
> Can you make sure of this? Because in given code I see nothing wrong. Should definitely work fine 🤔

Yes im sure.
and i just deleted the Svelecte component and my site now displays properly on Safari
:(

**Comment by mskocik** [comment]
Before I try to fix that. Try commenting all svelectes and ucomment them one by one, which one is throwing the error

**Comment by mskocik** [comment]
Btw your site is working fine in Firefox. It takes longer before the first svelecte appears, but it works fine. Also try adding `virtualList` property. It's false by default, but if you have long lists it can be faster to render.

**Comment by rocamalo** [comment]
Thanks i'll give it a try and let you know if it works!

**Comment by mskocik** [comment]
@rocamalo have you tried it? Can I close this issue?

**Comment by rocamalo** [comment]
it worked, you can close the issue, thanks a lot.
