### ISSUE TITLE
allow to focus the input using a `<label>` tag

### ISSUE THREAD

**Issue by lionelB** [mskocik/svelecte#72]
Hello

svelecte don't support `id` props which could be useful for focusing a input using its label (like other html input)
Would you accept a PR ?

**Comment by mskocik** [comment]
> Would you accept a PR ?

Of course! Please name that prop `inputId` so it will be clear what is it for. 
And add it to `Readme` and ideally also to docs HTML file

**Comment by lionelB** [comment]
I update my PR
