### ISSUE TITLE
"Uncaught TypeError: scrollContainer is null"

### ISSUE THREAD

**Issue by Augustin82** [mskocik/svelecte#76]
Hi!
We use Svelecte as a svelte component on a page, in a form component. Upon successful submission, another component is shown (this is done in an `{#if}{:else}{/if}` block.
When this happens, we get an error in the console:
```
Uncaught TypeError: scrollContainer is null
    positionDropdown Dropdown.svelte:97
    dropdownStateSubscription Dropdown.svelte:159
    dropdownStateSubscription Dropdown.svelte:159
    set index.mjs:34
```
After looking into it, it seems the following condition is bad:
```javascript
    console.log({scrollContainer, renderDropdown}); // added by myself
    if (!scrollContainer && !renderDropdown) return;
    const outVp = isOutOfViewport(scrollContainer.parentElement);
```
because it will not return when `renderDropdown` is not nullish.
Indeed, here is what I could log to the console: `Object { scrollContainer: null, renderDropdown: true }`.

Unfortunately, I don't understand enough of the reason for the issue to offer a fix for now, but I'd be glad to if you can shed some light on it for me =)

Cheers!

**Comment by mskocik** [comment]
If you could create reproducible example in svelte REPL, it would be very helpful

**Comment by Draconizations** [comment]
I am getting the same error in my svelte app. I've found out that if a component with a svelecte component inside it gets destroyed, these errors appear when scrolling. Here's a [link to a REPL](https://svelte.dev/repl/2576d9160e15473cb38ef72217e81d01?version=3.44.3) that reproduces the issue

**Comment by mskocik** [comment]
@Spectralitree thanks for your REPL, made it very easy for me to fix this 👏 💯

**Comment by Augustin82** [comment]
Hi! Thank you very much =)
