### ISSUE TITLE
Issue with multiple components with fetch

### ISSUE THREAD

**Issue by Tam2** [mskocik/svelecte#79]
I have multiple Svelecte components on my page which fetch their data using the fetch property from an api endpoint.

However having more than on eon the page causes only one of them to load data, i can see from the console logs the actual fetch call is made for both, but the first input simply shows as loading

Example on the repl, you'll notice the first input doesn't ever load

https://svelte.dev/repl/7be51477f8364632b8d6c763dcfb8247?version=3.46.2

**Comment by Tam2** [comment]
@mskocik - I've updated to 3.5.3 but it doesn't appear to have resolved the issue

I'm also using a fetchCallback to format the response back from the fetch if that make any difference (It works when there is only one on the page)

**Comment by mskocik** [comment]
Strange, because I have tested it and REPL is also working fine. Can you provide broken example?
Custom `fetchCallback` should not affect this

**Comment by Tam2** [comment]
Updated the REPL with the fetchCallback where it's not working

https://svelte.dev/repl/7be51477f8364632b8d6c763dcfb8247?version=3.46.2
