### ISSUE TITLE
Options groups in selection

### ISSUE THREAD

**Issue by PlkMarudny** [mskocik/svelecte#84]
Is there any way to get also **group** label in value/selection?

**Comment by mskocik** [comment]
If you provide it as an option property and then use your own `renderer` (which will handle displaying it) then yes.
Otherwise there is no way to get that information. Group label is handled as unselectable option in dropdown and acts only as a visual helper.

**Comment by PlkMarudny** [comment]
Basically this means a "group" should be added to each item, well, fine. Thank you.
