### ISSUE TITLE
Max options need to be {max}

### ISSUE THREAD

**Issue by superseby2** [mskocik/svelecte#85]
Sorry to open a issue for what could be obvious to many  but trying to use the  "max" option on my Sveltecte component did not work. 
It's only after some fiddling that I realized I needed to pass it as {2} (for a max equal to 2) in order for it to be handled properly as int. 

It's how it needs to be done in Svelte but maybe a hint in the documentation would help or a parseInt on the prop value would help . 

Thx for this component!

**Comment by mskocik** [comment]
Agree, can be confusing for those whose start with Svelte. Should be handled by #49
