### ISSUE TITLE
An option to show "Create with CTRL+Enter" only when there is no suggestion available

### ISSUE THREAD

**Issue by superseby2** [mskocik/svelecte#86]
Maybe this option exists but I could not find it.

Currently when a user starts typing, suggestions are shown and if creatable is true, the ability to create an new entry will be available. Which could be confusing for users. 

For instance in our implementation tying : 'python' shows the proper suggestion "Python" but also a message asking to create "python". 
Is there a way either disable entirely the the question or show it only when no suggestions are found? 

Thx!

![image](https://user-images.githubusercontent.com/32198925/152203297-58d53f97-3891-421d-84c1-1487e87cc54c.png)

**Comment by mskocik** [comment]
I am not sure if you mean `creatable` option. It would disable possibility to add new options completely.

Otherwise you can use `createFilter` for it? Like [this example](https://svelte.dev/repl/261222a20c6e4ac3ac635537f8d761dd?version=3.46.4)?

**Comment by mskocik** [comment]
@superseby2 any feedback on previous comment? Was the proposed solution enough for your use case?

**Comment by superseby2** [comment]
Sorry for the delay @mskocik 

I forgot to mention that I am using 'fetch' as well. 
So my problem is : when starting to type, I am successfully retrieving the list of relevant options from my Fetch async func but I am still being able to create a new item while I would be perfectly happy with the options I have. 
The risk here is, for me, to have doublons. 

What worked for me is changing line

`{#if inputValue && creatable && !maxReached}`
to 
`{#if inputValue && creatable && !maxReached} && (!items.length || items.length == 0)`

which assures me that I would be able to create a new option only when I have no other options available. 

This suits my use case. Not sure if this could be interesting to others and if an option like
"createOnlyWhenNoOption" would be relevant.

**Comment by mskocik** [comment]
@superseby2 I've extended arguments for `createFilter` function.

Take a look at [REPL](https://svelte.dev/repl/1e05f3f5388a44e187bdb6d6c6b5a0eb?version=3.46.4), how you can use it for your use case.

**Comment by superseby2** [comment]
Thank you @mskocik! It works like a charm :+1:

**Comment by superseby2** [comment]
@mskocik Not a big deal, but it appears that we introduced a side-effect. 
To reproduce with [REPL](https://svelte.dev/repl/1e05f3f5388a44e187bdb6d6c6b5a0eb?version=3.46.4)
- type python
- when you have the selection selected, you are allow to "arrow-down" which deselects the option and might confuse.
