### ISSUE TITLE
It is resorting my items

### ISSUE THREAD

**Issue by mspanish** [mskocik/svelecte#90]
Hi I have a 2000+ dataset, an array of objects that I load via fetch, and they are already alphabetized. For some reason this script and all others like it so far are re-ordering my items in a non alphabetical order. In my case, the field I have pre-alphabetized by is "sign". I've tried different settings - but it always messes up the order of my items no matter what I do. Can you see what I'm doing wrong?

`	<Svelecte options={$words}
	  valueAsObject=true
	  valueField="sign"
	  labelField="sign"
	  virtualList=true
	  lazyDropdown=false
	  disableSifter=true
	  sortField="sign"
	  searchField="sign"
	  bind:value={word}
	  placeholder="Find a word"
	></Svelecte>`

**Comment by mskocik** [comment]
Can you provide small subset of `$words`?
