### ISSUE TITLE
The 'allowEditing' option does not seem to work

### ISSUE THREAD

**Issue by acidtv** [mskocik/svelecte#92]
First, I'd like to thank you for building Svelecte. It is very useful to us!

I just tried the 'allowEditing' option with the 'complex playground' example. 
After having selected an item (from the 'Colors' set) using backspace removes the selection instead of editing it.

**Comment by mskocik** [comment]
You can use `allowEditing` only together with `creatable`. Because it make sense only for this use case

**Comment by acidtv** [comment]
Ah, I didn't know that.

We have selectbox without `creatable`, but with a lot of items (using `fetch`), so it would be useful to 'edit' your selection if you want to search for something else. But I think that would be a new feature then?

In any case, is it possible to update to docs to clarify that `allowEditing` only works when `creatable` is enabled?

Thanks!

**Comment by mskocik** [comment]
I am not sure I understand your use case.

If you want to search for something else (what is not among fetched items), you need to have set `creatable` to create option anyway.

If you would like to be able to edit fetched options, you need your items to have `$created: true` property. Like here: [REPL](https://svelte.dev/repl/b62c548e09ea4297a19ee0bef0998920?version=3.46.4)

**Comment by acidtv** [comment]
No, I don't want to create any new items.

What I mean is, say you have a long list of names of people and you want to find someone called 'Joe'. You type 'Joe' in svelecte to search for every name containing 'Joe' and you pick 'Joe Foobar'. After you have picked a name you realize you actually wanted to pick 'Joe FoobaZ'. If you could just use backspace to remove the 'r' and search for 'Joe Fooba' that would be very convenient.

**Comment by mskocik** [comment]
I see now, this is not supported at the moment.

But passing `fetchResetOnBlur` can help - it at least won't reset previously fetched results.

**Comment by acidtv** [comment]
Thanks, I'll have a look at that.
