### ISSUE TITLE
Add an option to use a search icon instead of the arrow

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#93]
Sometimes you might want to use Svelecte as search rather than drop down. It would be nice to have an option to switch from arrow to a search icon to indicate that. Some kind of parameter `is_arrow` or `icon_type`.
If you think this is a reasonable change, I'm happy to create a Pull Request for this.

**Comment by mskocik** [comment]
Could be added 🤔 The simplest solution would be to wrap current icon in a `slot`. If would offer more flexibility. 

PR would be simple. Basically duplicate the `icon` slot of `Control` component. And add example to custom icon example component in  docs.

**Comment by maxkozlowski** [comment]
Sounds good. I'll look into it in a couple of days and add a PR :+1:

**Comment by mskocik** [comment]
@maxkozlowski actually I tried this approach and it worked even without code modification. See [REPL](https://svelte.dev/repl/033d47cbc24743c182fc1b8ca67aae9a?version=3.46.4)

Basically I hiding original svg by making it transparent and only display custom svg as a background image.

So I don't think, PR for this is needed. Is this enough for your use case?

**Comment by maxkozlowski** [comment]
That looks awesome @mskocik , definitelly enough for my use case! Thanks a lot!
