### ISSUE TITLE
Can't import getSelection

### ISSUE THREAD

**Issue by maxkozlowski** [mskocik/svelecte#94]
Hello,

I'm trying to use getSelection but I can't import it. I was trying to:
`import Svelecte, {getSelection} from "svelecte";` but that throws an error :confused:
I wonder why could that be? (I'm likely just doing something wrong, forgive me- I'm new to both `js` and `svelte` 🙈 )

Thanks!

**Comment by mskocik** [comment]
Why would you want to import it? Method `getSelection` is exposed on `Svelecte` component, but it's used internally for custom element version.

In pure svelte you can use it like this (but it doesn't make sense). Because you can bind it's value to some property.

```svelte
<script>
import Svelecte from "svelecte";

let mySvelecte;

onMount(() => {
  mySvelecte.getSelection();
})

</script>

<Svelecte bind:this={mySvelecte}></Svelecte>
```

**Comment by maxkozlowski** [comment]
Ah I see what you mean, that makes sense. Thank you!
