### ISSUE TITLE
Make encodeURIComponent() for newly created options optional

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#95]
Hi, new options created with `creatable` prop are forced to go through encodeURIComponent() which should really not be forced. We should have full control over it. Would it be possible to make it optional or better - make it a callable prop we can set so we can transform the value ourselves. I know we cna kinda workaround it by using createEvent to modify it, but that's not a clean solution if multiple listeners are binded.

![obrazek](https://user-images.githubusercontent.com/10332247/157411335-9d067854-9bd3-41a1-94cb-f61c8ff0ff88.png)

![obrazek](https://user-images.githubusercontent.com/10332247/157411630-6fe8d9b5-9a52-4e92-8fd1-73998414ae76.png)

**Comment by mskocik** [comment]
Note for myself: this was implemented just for custom-element.
