### ISSUE TITLE
Removes unknown options on mount, even with `creatable` flag

### ISSUE THREAD

**Issue by avimar** [mskocik/svelecte#96]
(Hi - this looks really cool!
A limitation I had with another select system was that it was giving the results as a complex object, but you have the `labelAsValue` option. And a lot more options.)

I have an issue where my auto-complete options may be lagging the actual full set of options.
I set `creatable` and the user can add in an option, that seems to work.  But if I set that option from an external upto date source, then upon loading, just that value disappears. It looks like the code here should handle this case, though: https://github.com/mskocik/svelecte/blob/1c91cefb29130e6a2b0f00ee625dc5cf9e3d7297/src/Svelecte.svelte#L606

(I'm getting a weird [object Object] in my list too)

It's not letting me save a test repo, but this shows the issue. Since creatable is on, I'd expect the initialization of "four" to work fine.

```
<script>
	import Svelecte from 'svelecte';

	
	let value = ['two','four'];
</script>

<Svelecte options={['one','two','three']} multiple 
					creatable creatablePrefix=""
					labelAsValue bind:value={value}></Svelecte>
<hr>
<pre>{JSON.stringify(value)}</pre>
```

**Comment by mskocik** [comment]
This is not possible with simple arrays in current implementation, because `value` is always derived from current options. Internally Svelecte checks for non-existing values and don't allow this inconsistent state.

The only way you can achieve your example is by using objects as value like this:

```svelte
<script>
  import Svelecte from 'svelecte';
  let value = [{v:'two'},{v:'four', '$created': true}];
</script>

<Svelecte options={[{v:'one'},{v:'two'},{v:'three'}]}
  multiple 
  creatable creatablePrefix="" 
  valueAsObject labelField="v" valueField="v"
  bind:value={value}
></Svelecte>
<hr>
<pre>{JSON.stringify(value)}</pre>
```
