### ISSUE TITLE
Documentation on styling (e.g. active border)

### ISSUE THREAD

**Issue by maku** [mskocik/svelecte#98]
I have really problems to style svelecte. 

E.g. I am not able to style the "active border"... 

It would be good to have a styling section in the documentation

**Comment by mskocik** [comment]
Good point. Styling customization was added later and I forgot to add it there.

**Comment by maku** [comment]
@mskocik in the meantime could you give me a concrete hint how to style the "acive border" (e.g. with a specific border color when the widget has the focus)? TIA

**Comment by mskocik** [comment]
Chech the styling in `src/Svelecte.svelte`. In the top are defined properties that you can easily copy and override by your css class which you assign to your Svelecte component

**Comment by maku** [comment]
@mskocik Yeah I tried several things before I wrote this issue (of course)

Here are my tries in svelte repl https://svelte.dev/repl/0b8330bef9bc432294ad78724e4ff889?version=3.46.4

**Comment by mskocik** [comment]
Almost there. Just add `!important` to your 

```css
:global(.svelecte-control) {
    --sv-active-border: 1px solid red !important;
}	
```

Or if you want complete restyle, do it like in this [REPL](https://svelte.dev/repl/cdb5f771e6734b4683494ec9239e47c9?version=3.46.4) (ie. copy whole `.svelecte-control` class and add `class` property to your Svelecte

**Comment by maku** [comment]
@mskocik yeah but this does not work for me 

```
:global(.svelecte-control) {
    --sv-active-border: 1px solid red !important;
}
```

see https://svelte.dev/repl/8798d125beaf4752b769eaf4312e9b93?version=3.46.4

**Comment by mskocik** [comment]
try this only 

```html
<style>
  :global(.svelecte-control) {
    --sv-active-border: 1px solid red !important;
    --sv-border-color: green !important;		
  }	
</style>
```

because your style `border-color` has higher priority

**Comment by maku** [comment]
Great this works, thank you very much...

**Comment by gterras** [comment]
Hi is it still expected to use `global` for basic styling? Passing a CSS variable to the component (`<Svelecte --sv-min-height="35px" />`) does not work since it is wrapped in extra markup . It also get overriden for any element that isn't the root `.svelecte-control` since the CSS variables are reapplied for each sub-element, example with 

```
<style>
	:global(.svelecte-control) {
		--sv-min-height: 32px ;
	}
</style>
```

**CSS variable is applied for top-level element:**

![image](https://user-images.githubusercontent.com/27226185/203777052-93c9a535-9452-4b81-8cc7-b20c8098fe05.png)

**But default comes back for any nested element:**

![image](https://user-images.githubusercontent.com/27226185/203776932-3c6fd916-9db1-4e62-91c8-c784c679dcb2.png)

**Comment by mskocik** [comment]
> Hi is it still expected to use `global` for basic styling?

Yes, this is still required. Why? Because I had written style override technique before it was possible to inline css vars in components.

I will open another issue for this, hopefully someone will create PR for it :)

**Comment by gterras** [comment]
> I will open another issue for this, hopefully someone will create PR for it :)

I'll try to have a look this weekend if I can find some time!

**Comment by faulander** [comment]
> Almost there. Just add `!important` to your
> 
> ```css
> :global(.svelecte-control) {
>     --sv-active-border: 1px solid red !important;
> }	
> ```
> 
> Or if you want complete restyle, do it like in this [REPL](https://svelte.dev/repl/cdb5f771e6734b4683494ec9239e47c9?version=3.46.4) (ie. copy whole `.svelecte-control` class and add `class` property to your Svelecte

The REPL is not available and if i copy whote .svelecte-control and change properties and add class=".svelte-control" to the elemenet, it's completely f**ed up. Any hints?

**Comment by mskocik** [comment]
> The REPL is not available and if i copy whote .svelecte-control and change properties and add class=".svelte-control" to the elemenet, it's completely f**ed up. Any hints?

Not sure, why the REPL doesn't work. Here is full working example:
```svelte
<script>
  import Svelecte from 'svelecte';	
  let options = ['one', 'two', 'three'];
</script>

<Svelecte {options}></Svelecte>

<style>
  :global(.svelecte-control) {
    --sv-active-border: 1px solid red !important;
  }
</style>
```

If you want to add custom class, use class name without starting `.` and it still needs to be defined as `global`, because compiler doesn't match `class` property on components with style.
