### ISSUE TITLE
Selected value is not showing up properly after init

### ISSUE THREAD

**Issue by FluffyDiscord** [mskocik/svelecte#99]
Hi,
I would like to ask you if it's okay why the `selected` eg. svelecte `value` is not updated properly on init. I am using this select in vanilla JS as a HTML select replacement and setting/accessing it's values outside of the svelte component which works fine, except that the binded `selected` property doesn't seem to update properly on init as accesing it returns empty object
```js
{0: undefined}
```

My wrapper component around your awesome select component:

```html
<svelte:options accessors={true}/>
<script lang="ts">
    import Svelecte from 'svelecte/src/Svelecte.svelte'
    import {createEventDispatcher} from "svelte";
    import {get_current_component} from 'svelte/internal'
    import {HTMLSvelteSelect, SvelteSelectOption, SvelteSelectOptionGroup} from "../Interface";

    const dispatch = createEventDispatcher()

    export let targetElement: HTMLSvelteSelect|null = null
    export let ajax: boolean = false
    export let ajaxRoute: null|string = null
    export let selected: SvelteSelectOption[]|SvelteSelectOption|null = []
    export let options: SvelteSelectOption[]|SvelteSelectOptionGroup[] = []
    export let renderer: string|Function|null = null
    export let multiple: boolean = false
    export let valueField: string = 'id'
    export let firstIfEmpty: boolean = false
    export let required: boolean = false
    export let disabled: boolean = false

    if(targetElement !== null) {
        targetElement.svelte = get_current_component()
    }

    const handleSvelecteChange = (e): void => {
        dispatch('change', e.detail)
        targetElement?.dispatchEvent(e)
    }

    const handleSvelecteCreateOption = (e): void => {
        // workaround for forced uri component encoding
        e.detail[valueField] = decodeURIComponent(e.detail[valueField])
        dispatch('createoption', e.detail)
        targetElement?.dispatchEvent(e)
    }

    const handleSvelecteFetch = (e): void => {
        dispatch('fetch', e.detail)
        targetElement?.dispatchEvent(e)
    }

    const handleSvelecteBlur = (e): void => {
        dispatch('blur', e.detail)
        targetElement?.dispatchEvent(e)
    }

    if(firstIfEmpty === true && (selected == null || selected.length === 0)) {
        let first
        if(Array.isArray(options[0]?.options)) {
            first = options[0].options[0]
        } else {
            first = options[0]
        }

        if(first) {
            selected = multiple ? [first] : first
        }
    }

</script>

<Svelecte
        {...$$props}
        {disabled}
        {required}
        {renderer}
        bind:value={selected}
        on:change={handleSvelecteChange}
        on:createoption={handleSvelecteCreateOption}
        on:fetch={handleSvelecteFetch}
        on:blur={handleSvelecteBlur}
/>
```

Creating my wrapper component
```ts
const options = [
    {
        "id": "CZ",
        "name": "Česko (+420)"
    },
    {
        "id": "SK",
        "name": "Slovensko (+421)"
    }
]

const instance = new MySelect({
        target: parent, // not relevant
        anchor: selectElement, // not relevant
        props: {
            options: options,
            selected: selected, // either null / one option object / array of option objects (if multiple)
            valueField: 'id',
            labelField: 'name',
            valueAsObject: true,
            targetElement: parent, // not relevant
            firstIfEmpty: true,
            virtualList: true,
            name: selectElement.getAttribute('name'),
            multiple: selectElement.multiple,
            ...props // not relevant
        }
    })
```

now I would expect that when nothing yet happened (no interaction from the user or other scripts) I would get the selected value on init,
 but I get something rather random and I am not sure why.
```ts
// returns {0: undefined}
instance.selected
```
Your select component does render proper select on the page with the selected value, but the property is not updated

Any tips ?

**Comment by mskocik** [comment]
I have no experience with svelte's generated custom components. But have you tried built-in custom-element version of svelecte? I am using it this way in PHP applications successfully.

Check this [REPL](https://svelte.dev/repl/da8cfeed91b448b4bdb2ecc8b1f8741c?version=3.44.1)

**Comment by FluffyDiscord** [comment]
I think I would run into the same issue as custom element props are also compiled the same way (they are public getters/setters on a dom element).

When I get a bit of free time, I will try using the custom element approach, but since I can't rewrite my whole app now to use the custom elements (I have done that once, migrating from jquery select plugins) 

Still, I am looking for a way to work around this issue using the current implementation, rather than rewriting the whole thing.

**Comment by mskocik** [comment]
You could try to bind the `selected` prop to Svelecte's internal method `getSelection` then. Maybe it will help.

**Comment by mskocik** [comment]
Or try including `dist/svelecte-element.js` and call 
`Svelecte.registerSvelecte()` to test custom element without the need to modificate your code.

**Comment by mskocik** [comment]
Okay, my latest comments were little bit off. One question - are you getting any messages in the console?

**Comment by FluffyDiscord** [comment]
Only `<Svelecte> was created with unknown prop 'XXX'` since I lazily pass all props via `{...$$props}`, nothing else as far as errors/warning goes

**Comment by FluffyDiscord** [comment]
Closing the issue.

When the select is set to a single value (multiple=false) and I try to assing the `value` prop array of objects Svelecte component can't handle it and returns `{0: undefined}` as selected item. It could check whenever it's an array and select first item, but that is more of a QoL rather than a bug.
